### ISSUE TITLE
DOS Failure On Disconnection

### ISSUE THREAD

**Issue by bikeath1337** [TTLabs/EvaporateJS#100]
Tried breaking EvaporateJS to see how it behaves and recovers from an internet connection failure.

Basically, the `sign_auth` request behaves differently and when connectivity is restored, Chrome decides to retry all of the errored requests, thus swamping the async queue.

For large uploads with hundreds of parts, this basically breaks Chrome. There are also resource issues because the list of Xhr objects that have been created, so even if the 1,000s of requests could be processed, they'd fail due to out of memory.

The fix is fairly easy. Will submit shortly for review.

**Comment by tomsaffell** [comment]
@bikeath1337 looks like this is fixed, right?

**Comment by bikeath1337** [comment]
Yes, closing.
