### ISSUE TITLE
.add() returns upload id

### ISSUE THREAD

**Issue by fivepapertigers** [TTLabs/EvaporateJS#106]
Hey, It would be helpful in the docs to say that the .add() function returns the upload id. I was wondering where to get the id so I could cancel an upload. It wasn't hard to figure out from the source code, but would still be helpful in the docs. 

Thanks for a great uploader. I'm upload big files to S3 no problem and it's a lifesaver.

**Comment by bikeath1337** [comment]
I corrected this in the next release branch.
