### ISSUE TITLE
InitiateUpload() and CompleteUpload() Should Retry on Failure

### ISSUE THREAD

**Issue by bikeath1337** [TTLabs/EvaporateJS#107]
`initiateUpload()` and `completeUpload()` should retry on failure in a similar fashion to UploadPart, respecting the backOff heuristics.

We fortuitously encountered an S3 internal error on `completeUpload` while we were going live with the md5 digest branch which prompted this report.

The reason retry is important is that if one is uploading multiple files in a "transaction" (for example, uploading multiple video clips for stitching into a single file), it's as important to retry the multipart upload level calls as much as the parts of a single file.

**Comment by tomsaffell** [comment]
@bikeath1337  this can be closed now, right?

**Comment by bikeath1337** [comment]
Yes, closing.
