### ISSUE TITLE
localStorage is not always available

### ISSUE THREAD

**Issue by bikeath1337** [TTLabs/EvaporateJS#116]
Local storage is not available when in incognito mode.

**Comment by SamPotts** [comment]
Safari's private mode seems to be the most painful in this regard in my experience. I wrote a suggested way to get around the issue that I use elsewhere in my PR.

**Comment by bikeath1337** [comment]
It is far easier to track issues separately and keep them separate in pull requests, so I am adding the distinct issues you bring up so they can be solved individually.

**Comment by SamPotts** [comment]
Sorry, I'm just trying to help.

**Comment by bikeath1337** [comment]
You are being helpful but it's important to keep issues distinct from each other so they can be solved in isolation wherever possible.
