### ISSUE TITLE
signParams Should Persist

### ISSUE THREAD

**Issue by bikeath1337** [TTLabs/EvaporateJS#117]
@SamPotts can you please fill this one in?

**Comment by SamPotts** [comment]
Resend the original `signParams` when retrying upload at a later time. This is useful for file or path specific tokens generated on the original signature request to be re-sent with subsequent signature requests.

**Comment by bikeath1337** [comment]
Thanks, @SamPotts .

I cherry picked the essence of your commits and pushed them to my fork as branch `rc1`. Would you like to test this out to see if it satisfies the issues you reported?

We can then look at the previous PR related to the initiate error handler.

**Comment by SamPotts** [comment]
Sure - will do first thing in the morning.
