### ISSUE TITLE
NPM is out of sync

### ISSUE THREAD

**Issue by todda00** [TTLabs/EvaporateJS#127]
The npm registry has 0.0.2 as the latest version, can NPM be updated to the latest copy 1.0.2?
https://www.npmjs.com/package/evaporate

**Comment by bikeath1337** [comment]
yes, will do...after work. thanks! :)

**Comment by bikeath1337** [comment]
@tomsaffell I think I need your help here.

**Comment by tomsaffell** [comment]
@bikeath1337 what do i need to do? I dont think I initially registered it with npm, but maybe I did?

**Comment by bikeath1337** [comment]
I can do a Ruby gem but I'm no NPM expert. @todda00 can you advise us so we can get this published correctly, please?

**Comment by bikeath1337** [comment]
@tomsaffell "savroff" owns this on NPM. I sent him an email. If you know him, perhaps you can reach out, too?

**Comment by tomsaffell** [comment]
@bikeath1337 i do not know him, sorry. 
but perhaps i can contact someone who runs npm (friend of friend) to get it switched. do you want to own it?

**Comment by tomsaffell** [comment]
or perhaps @todda00 should own in on npm?

**Comment by todda00** [comment]
I have never owned anything in NPM, I have only used it to pull in
packages, but can look into it if you would like. I am on vacation next
week but can look into it the week after.

**Comment by bikeath1337** [comment]
Thanks @todda00 . I got access from the original gent who pushed it.

**Comment by tomsaffell** [comment]
@bikeath1337 so you dont need me to email the npm managers, right?

**Comment by bikeath1337** [comment]
Nope.

**Comment by bikeath1337** [comment]
I published 1.0.2.
