### ISSUE TITLE
Canceling queued upload throws error

### ISSUE THREAD

**Issue by SamPotts** [TTLabs/EvaporateJS#135]
When cancelling a queued upload (which has no uploadId, of course), the abort request fails because uploadId is missing, throwing an error incorrectly. I believe the fix is adding the following to [line 668](https://github.com/TTLabs/EvaporateJS/blob/master/evaporate.js#L668) before the abort request is sent: 

```javascript 
if(typeof me.uploadId === 'undefined') {
    setStatus(ABORTED);
    return;
}
```

To recreate: add 2 files and cancel the 2nd before the upload begins.

**Comment by bikeath1337** [comment]
Thanks, @SamPotts , want to submit a PR?

**Comment by SamPotts** [comment]
Will do!

**Comment by bikeath1337** [comment]
@SamPotts I'm looking around and can't seem to find if you submitted a fix for this or not. Can you help my fading memory?

**Comment by SamPotts** [comment]
Sorry, it skipped my mind - just sent you it... 👍

**Comment by bikeath1337** [comment]
Thanks!
