### ISSUE TITLE
Specifying allowable size for the uploaded content with "content-length-range"

### ISSUE THREAD

**Issue by n-0** [TTLabs/EvaporateJS#136]
Is there a way to limit the maximum allowed file size? I tried with

`xAmzHeadersAtInitiate : {
            'content-length-range': '0, 485760'
          }`

but it doesn't work: 
"The request signature we calculated does not match the signature you provided."

**Comment by tomsaffell** [comment]
if you want to apply the client side (not very secure, but perhaps you dont mind that?), then probably easiest to do the check before you pass the file reference to evaporateJS. if you want it enforced server side, then ideally it would be implemented as an S3 policy (I dont know whether that's possible - I suggest you check). Failing that, best to implement it in your signing function.

**Comment by n-0** [comment]
As long I understand it is not possible to enforce it server side with a S3 policy.
About implementing it in the signing function, I think it still depends on the front-end.
Thanks

**Comment by bikeath1337** [comment]
I think this is worth considering as an enhancement to EvaporateJS and will submit a pull request for review.
