### ISSUE TITLE
Fails with 301 PermanentRedirect

### ISSUE THREAD

**Issue by olivierlesnicki** [TTLabs/EvaporateJS#137]
My bucket is in Ireland - which I believe could be the reason why the url: `https://s3.amazonaws.com/bucket` doesn't work

```
<Error>
<Code>PermanentRedirect</Code>
<Message>
The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.
</Message>
<Bucket>bucket</Bucket>
<Endpoint>bucket.s3.amazonaws.com</Endpoint>
<RequestId>xxx</RequestId>
<HostId>
xxx
</HostId>
</Error>
```

**Comment by tomsaffell** [comment]
@olivierlesnicki Please can you tell us what steps lead to this error, where the error is being shown, and what behavior you would expect instead of this error?

**Comment by olivierlesnicki** [comment]
Hey @tomsaffell, it's as simple as trying to use evaporate.js with a bucket set in a non US location (Ireland) for example.

When using the API for bucket outside of US it is necessary to use the url as `bucket.s3-region.amazonaws.com` instead of `s3.amazonaws.com/bucket`.

While evaporateJS offer a way to specify the `aws_url` it appends the bucket name out the end of the url. Making it impossible to use the correct url format S3 is expecting.

**Comment by olivierlesnicki** [comment]
See http://docs.aws.amazon.com/general/latest/gr/rande.html
Chapter: Amazon Simple Storage Service (Amazon S3)

![image](https://cloud.githubusercontent.com/assets/1705944/14580106/03d10c78-03bb-11e6-80f6-20b0e9dddca8.png)

**Comment by bikeath1337** [comment]
@olivierlesnicki , EvaporateJS should support your use case with the following config options enabled. You have to set the `cloudfront` and `awsUrl` options. This example uses a bucket named `my-bucket`. You can test this by using the correct AWS host for your region.

```javascript
    var evaporate = new Evaporate({
        cloudfront: true,
        aws_url: 'https://my-bucket.s3.amazonaws.com'
    });
```

**Comment by SpareShade** [comment]
Great! This helped me solve my problem :) but I had to specify bucket too:

```js
    var evaporate = new Evaporate({
        bucket: 'my_bucket',
        aws_url: 'https://s3-ap-southeast-2.amazonaws.com'
    });
```
Thank you!!

**Comment by bikeath1337** [comment]
Glad to help.
