### ISSUE TITLE
Re-uploading an existing file to a new AWS key tries to resume an upload to the original key

### ISSUE THREAD

**Issue by cnorthwood** [TTLabs/EvaporateJS#139]
So I have a use case where a user might want to upload the same file to different buckets/keys, but right now if the same file is selected, then it fetches it out of localStorage and tries to resume the upload to an existing key. I'd like to alter the logic so it'll only resume the upload if the key hasn't changed (I believe it needs to be done around here https://github.com/TTLabs/EvaporateJS/blob/master/evaporate.js#L881)

I'll raise a PR for this tomorrow unless anyone objects?

Thanks

**Comment by bikeath1337** [comment]
Hi, there, that sounds fine to me as long as the improvements don't change existing behavior with the existing configuration options. Whatever we do should be built such that users wanting this feature, have to explicitly enable it, methinks.

But going back to your mentioning different "_buckets_/keys" I think it's important to note that Evaporate only supports a single bucket, so if changing buckets is part of the problem, then we need to consider adding the bucket name in place when the upload data was "cached" to local storage.

**Comment by cnorthwood** [comment]
I guess I'm trying to figure out if the existing behaviour is a bug or not :) If you specify a name into evaporate, but the file matches a file that's been uploaded previously, it disregards the name you specified and re-uses the one that it was previously.

My workflow is that the signing server issues object names and then only allows signs requests from that user which match a name that has been issued to them. When an upload completes then the object name is marked as uploaded and published into the CMS for use, and a user can't upload that any more. When a user picks the same file again, then a new object name is issued to the client, but when Evaporate sends the signing requests to the server, it uses a different object name. That seems like a bug to me. I'd like to change it so uploads only get resumed if the file hash (as now) as well as the bucket/name match.

**Comment by bikeath1337** [comment]
I think we addressed this in #140
