### ISSUE TITLE
Refused to get unsafe header "ETag"

### ISSUE THREAD

**Issue by diegoloredo** [TTLabs/EvaporateJS#142]
I made an implementation of EvaporateJS and Python based on the example of the file evaporate_example.html but im passing for two cases. 

The One is when i try to send the file to S3 for the first time, it returns to me this error "Refused to get unsafe header ETag" that is rised by this line  https://github.com/TTLabs/EvaporateJS/blob/master/evaporate.js#L449. At the end of all it returns to me a message of error telling me that is missing a part. 

The Second is when i try the to upload the same file (key) again it returned a message of complete, like it worked but when i found the file at S3 the file became smaller. (Because it missing a part) 

So, i don't know how to solve the problem of the subject but my suggestion is to not return a message of "complete" one time that it is missing parts.

There is my implementation code:
Evaporate JS: http://pastebin.com/aqcHpHsc
Django: http://pastebin.com/Wjv1BDXE

**Comment by bikeath1337** [comment]
@diegoloredo you haven't set you CORS configuration for your bucket correctly. The readme shows an example in Step 3. Please read it and correct your configuration.

Once that is complete, the rest of your code may work.
