### ISSUE TITLE
AWS Policy support

### ISSUE THREAD

**Issue by DrySs** [TTLabs/EvaporateJS#145]
Hi there,

We are trying to move from jQuery.fileUpload() to EvaporateJS in order to handle multi-part transfert.

But we cannot find anywhere to custom our policy.

Indeed, we were generated (using server PHP script) an upload policy, with an expiration rights and some conditions (bucket to write, acl, key filename):

```
    function getUploadPolicy($key)
    {
        $policy = json_encode(array(
            'expiration' => date('Y-m-d\TG:i:s\Z', strtotime('+6 hours')),
            'conditions' => array(
                array('bucket' => $this->bucket),
                array('acl' => 'private'),
                array('starts-with', '$key', $key),
                array('success_action_status' => '201')
            )
        ));
        return base64_encode($policy);
    }
```

How to proceed to implement this restrictions?

Thanks for your help :)
Philippe

**Comment by DrySs** [comment]
Until now, we are using our policy (returned by getUploadPolicy() function) for our signature:

`
$key = 'mydirectory/myfile.mp4';
$policy = getUploadPolicy($key);
$signature = base64_encode(hash_hmac('sha1', $policy, $AWSSecretKey, true));
`

But with Evaporate, signature must be signed with a "to_sign" variable.

Should "to_sign" variable be considered as policy?
How to setup it?

**Comment by bikeath1337** [comment]
@DrySs , no, the `to_sign` parameter is used to calculate an AWS V2 signature. You use the policy method only when uploading directly from a browser's HTML FORM element. 

There is no fundamental need to deal with policies at the client. We set our bucket policies using the AWS console and associate it with the IAM user defined in the signing controller. If you want to pass specifics like ACL in the header, you can do that. Instructions, I think, are in the readme for our project. We also provide sample policies you can use as a template for the AWS policy editor.

To create a V2 signature from the `to_sign` parameter , you'll need the following bits of information. Make sure to not expose your secret key anywhere in your codebase....

1. your AWS_SECRET for the AWS account you're using.
2. you'll need to encode the `to_sign` and `aws_secret` as UTF-8
3. you'll need a SHA1 digest function
4. and an HMAC function to create your signature
5. which then needs to be chomp'ed.

This is how it's done in Ruby:

```ruby
  def sign_data(details_to_sign)
    aws_secret = Rails.application.secrets.AWS_SECRET || ENV['AWS_SECRET']
    secret = aws_secret.encode('UTF-8')

    details = details_to_sign.encode('UTF-8')
    sha1 = OpenSSL::Digest::Digest.new('sha1')
    hmac = OpenSSL::HMAC.digest(sha1, secret, details)

    return Base64.encode64(hmac).chomp()
  end
```

I think that PHP would look something like this:

```php
$secret = base64_encode($AWS_SECRET);
$details = base64_encode($TO_SIGN);
$hmac = hash_hmac('sha1', $details, $secret, true);
return  rtrim(base64_encode($hmac), "\n");
```
Here is a link to the AWS page on V2 Signatures and the REST API (what EvaporateJS uses):

http://docs.aws.amazon.com/AmazonS3/latest/dev/S3_Authentication2.html

**Comment by bikeath1337** [comment]
Closing this as I think you have been helped regarding the role of Policies with EvaporateJS.
