### ISSUE TITLE
Signature 4: server-side example and cryptoHmacMethod

### ISSUE THREAD

**Issue by pauldijou** [TTLabs/EvaporateJS#157]
First of all, thanks a lot for supporting Signature 4.

I did found [an example](https://github.com/TTLabs/EvaporateJS/blob/master/example/evaporate_example_awsv4_signature.html) for the client-side but none for the server-side. Is there any plan to have it in one or two languages in order to help understanding how to generate the signature expected by Evaporate just to be sure?

Also, I couldn't find any usage of `cryptoHmacMethod` inside Evaporate code source. There is a check to validate it's a function if signature 4 is enabled but after that, looks like it's never used. Am I missing something?

cc @bikeath1337

**Comment by bikeath1337** [comment]
@pauldijou you're right about the unused option. I've got a WIP to remove it. I also have some Ruby on Rails controller code that I used to build the enhancement.

**Comment by bikeath1337** [comment]
@pauldijou , I added #161 to address these issues. Would you like to review to see if they help?

AWS provides a Python example here http://docs.aws.amazon.com/general/latest/gr/sigv4-signed-request-examples.html.

This is essentially the core Python code that does the same thing as my Rails Controller:

```python
# Key derivation functions. See:
# http://docs.aws.amazon.com/general/latest/gr/signature-v4-examples.html#signature-v4-examples-python
def sign(key, msg):
    return hmac.new(key, msg.encode('utf-8'), hashlib.sha256).digest()

def getSignatureKey(key, dateStamp, regionName, serviceName):
    kDate = sign(('AWS4' + key).encode('utf-8'), dateStamp)
    kRegion = sign(kDate, regionName)
    kService = sign(kRegion, serviceName)
    kSigning = sign(kService, 'aws4_request')
    return kSigning

# Create the signing key using the function defined above.
signing_key = getSignatureKey(secret_key, datestamp, region, service)

# Sign the string_to_sign using the signing_key
signature = hmac.new(signing_key, (string_to_sign).encode('utf-8'), hashlib.sha256).hexdigest()
```
