### ISSUE TITLE
README incorrect?

### ISSUE THREAD

**Issue by pauldijou** [TTLabs/EvaporateJS#158]
Not sure about that, but I think the README is a bit wrong on the `.add` function since 1.4.0.

```markdown
evap.add(file[, config])

- file: File. a reference to the file object
- config: Object. Optional. Used to override the configuration options passed when instantiating EvaporateJS (for the added file only).
```

As I understand it, `file` should a real [File](https://developer.mozilla.org/en-US/docs/Web/API/File), but that would not only be a breaking change (since it was `{name: String, file: File}` before) but it wouldn't work with the current source code (there is no [file.file](https://github.com/TTLabs/EvaporateJS/blob/master/evaporate.js#L300) property on a `File` object).

So my guess is that `file` is the same object as on previous versions but the README doesn't describe it correctly. What do you think?

cc @bikeath1337

**Comment by bikeath1337** [comment]
Thanks, @pauldijou . I added pull request #160 to address this. If you could, please check it out.
