### ISSUE TITLE
Allow users to select files but don't upload immediately

### ISSUE THREAD

**Issue by njbmartin** [TTLabs/EvaporateJS#159]
I'd like to suggest a new config option to not upload immediately after selecting files, but instead let the user hit a button to start the upload queue.

**Comment by bikeath1337** [comment]
@njbmartin , EvaporateJS sample HTML files use the "onChange" event on the file input as a convenience to illustrate how it all works. You are free to create you own user interface that submits a file to upload when your user clicks a button.
