### ISSUE TITLE
Support  programmatic pausing and resuming

### ISSUE THREAD

**Issue by evadne** [TTLabs/EvaporateJS#17]
EvaporateJS should support cancellation or expose a way to cancel things easily. Each upload can be represented as an individual object which exposes observable progress, and allows cancellation, pausing, and resumption.

Update: Cancellation seems already supported.

**Comment by bikeath1337** [comment]
Now that v1.0.0 can cancel uploads correctly and we can automatically resume failed uploads, something tells me this feature request would look different. Any thoughts?

For example, what does "pause" mean? Does it mean..stop now? Or does it mean "stop after you're done with all currently-uploading parts"?

In any case, v1.0.0 makes this feature easier.

I know that for my place of work, we don't need the pause button because of the auto-resume feature.

**Comment by tomsaffell** [comment]
@bikeath1337 those are definitely the right questions!  I believe there is a PR related to this, but it may not be compatible with v1.0.0

We have `cancel()`, which stops all network activity for that file, and irreversibly removes the parts already uploaded. That's useful, and appropriately named, IMO. 

The use case I can see for pausing and resuming is: We have crappy uplink at our office, and EvaporateJS hogs it all, which makes t'Internet slow for everyone else. We'd like to be able to 'pause' *all* uploads, and then 'resume' at a better time (end of day, etc). 

A similar use case is that there are 2 files in the queue, first one big, second one small. It starts on the first one, but you want the smaller second one to go through first. You could 'pause' just the first one, then resume it when the second one is done. That gets a little complicated..

@evadne can you describe the exact use cases that you're thinking of? That will help refine this.

**Comment by bikeath1337** [comment]
Ah, yes! But that really leads me to the next enhancement request: the ability for a user to choose the parallelization optimal for his/her connection speed.

This could mean:
- utilizing multiple hosts to the same S3 bucket (working around browser limits to a single host)
- allowing part size to be manipulated
- allowing concurrent parts (and files) to be manipulated.

But for now...let's see how v1.0.0 does. hah.

**Comment by bikeath1337** [comment]
I added a PR that attempts to address this effectively. Refer to #184.
