### ISSUE TITLE
Discussion: Move to release 2.0 - Discard legacy support

### ISSUE THREAD

**Issue by red010b37** [TTLabs/EvaporateJS#177]
Hi all.

So I have been deep diving in the to code and different releases. There seems to be lots of issues an complexity surrounding legacy support of EvaporateJS and AWS. This seems to be complicating in the support of the project and adding unnecessary overhead.

I looked at the s3 regions (http://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region) and they all support sig V4 and the new regions only support V4.

I propose we move to EvaporateJS v2.0 and remove support of legacy EvaporateJS and Support of  Aws Sig2.  Yes these are breaking changes hence the v2.0 but this will eliminate a lot of code complexity, fall in line with amazon and set it up for easier maintenance going forward.

Im happy to help out as this project is critical to my app but at the moment I cant find a release that works 100% as it should.

Thoughts?

**Comment by njbmartin** [comment]
I can agree with that. @bikeath1337 was actually talking about rolling back the recent changes as there's a lot of work for backwards compatibility.

This is probably the better option. Separate branch for maintaining compatibility for a while longer?

**Comment by bikeath1337** [comment]
I am happy to revert the changes.

**Comment by red010b37** [comment]
@bikeath1337 @njbmartin  - its up to you guys about the revert as my project knowledge is limited. But I do agree with the separate branch moving forward.

**Comment by bikeath1337** [comment]
I am only in favor of refactoring if we first start with tests against the existing behavior. Any suggestions for the test framework?

**Comment by bikeath1337** [comment]
In v2.0, I was able to make the signing algorithms pluggable and split up the functionality into small modules (albeit they are still in a large closure). And this version has about 225 tests and counting.
