### ISSUE TITLE
1.4.1 - v4 Sig with different data center uploads to folder with the same bucket name

### ISSUE THREAD

**Issue by red010b37** [TTLabs/EvaporateJS#178]
Hi,

Uploading a file to say the Sydney endpoint with the v4 sig uploads it folder in the bucket with the same name as the bucket.

e.g
`syd_bucket/syd_bucket/filename`

I see that getPath only accounts for the cloud front url - however changing this then causes a 403

**Comment by njbmartin** [comment]
This is one of the issues I was trying to resolve again with backwards compatibility (PR #173)

**Comment by bikeath1337** [comment]
@red010b37 can you try this with v1.4.4? I just restored the correct behavior and reverted the incorrect documentation changes.

**Comment by bikeath1337** [comment]
Use the "cloudfront" option. It turns the url into the one you're looking for: bucket.awss3.com

**Comment by bikeath1337** [comment]
If you only set it once, then set when you instantiate EvaporateJS.
