### ISSUE TITLE
Add withCredential support

### ISSUE THREAD

**Issue by HugoCrd** [TTLabs/EvaporateJS#179]
Hi!

For now XMLHttpRequests are done without setting `withCredential(true)`. It would be great to allow this to be defined in configuration.

I forked EvaporateJS for my use case and did this :
https://github.com/Melusyn/EvaporateJS/commit/0846a7db13c6a29585e1cdf9ec93ea02d866e480
which resolve my problem, but having an official option (opt-in) would be great!

Cheers

**Comment by bikeath1337** [comment]
See PR #181 . Let me know if this addresses the issue.

**Comment by bikeath1337** [comment]
Addressed in #181
