### ISSUE TITLE
European buckets and changing aws_url on the fly

### ISSUE THREAD

**Issue by HugoCrd** [TTLabs/EvaporateJS#180]
Hi!

I'm using an european bucket.

**Signatures have to follow this pattern :**
```
to_sign:"POST
  application/xml; charset=UTF-8
  x-amz-date:Fri, 22 Jul 2016 12:36:25 GMT
  /my-bucket/name.JPG?uploadId=...."

datetime:"Fri, 22 Jul 2016 12:36:25 GMT"
```
*Note how `my-bucket` is placed here `/my-bucket/name.JPG?uploadId=....`*

**Following part uploads URI have to follow this pattern :** 
```
https://my-bucket.s3.amazonaws.com/name.JPG?uploadId=...
```
*Note that `my-bucket` is now part of domain*

For now I can't find any way to do such thing with Evaporate.

**AWS_URL**

In my use-case, bucket is specified dynamically by another request so I don't know which bucket will be used when instantiating Evaporate.
As bucket name is part of amazon domain (`https://my-bucket.s3.amazonaws.com`) I have to change aws_url on the fly.

**My hack and questions**

I did a hack to answer this use-case that you can find here :
https://github.com/Melusyn/EvaporateJS/commit/65dec4885ea1fd32ee7f0e513ef1bd72896a0d64

But I find it too much hacky. How do you manage such use-cases? Why AWS_URL is globally set and not allowed to be changed?

Anyway, thanks for this great library ;)

**Comment by bikeath1337** [comment]
@HugoCrd , assuming you are using V4 signatures, which I believe is mandatory for European regions, you should be able to override the bucket name when you add the file (make sure to use v1.4.4).

```javascript
         var files;
         
         var _e_ = new Evaporate({
            aws_key: '<aws_key>',
            bucket: '<bucket-name>'
         });
      
         $('#files').change(function(evt){
            files = evt.target.files;
            
            for (var i = 0; i < files.length; i++){
            
               _e_.add({
                  name: 'test_' + Math.floor(1000000000*Math.random()),
                  file: files[i],
                  complete: function () {  },
                  progress: function (progress) {     }
               },
               // override options for the file:
               {
                   bucket: '<file-bucket-name>'
                });
            }
            
            $(evt.target).val('');
            
         });
```

**Comment by HugoCrd** [comment]
Well I'm not using v4 signature as Ireland still support v2. That why I faced this problem.

But I now understand that v4 signature would solve this : I may migrate to v4 so I don't have to fork evaporate.js (I will have to, eventually).

Thanks for the tip, I'll have a look.

**Comment by bikeath1337** [comment]
The cloudfront  option should do it for you with v2

There is something to this effect on the reader

--
Bobby
646-321-6011

**Comment by bikeath1337** [comment]
Use the "cloudfront" option. It turns the url into the one you're looking for: bucket.awss3.com
If you only set it once, then set it when you instantiate EvaporateJS.

**Comment by HugoCrd** [comment]
Well, `cloudfront : true` option does turns url into` bucket.s3.amazonaws.com`.
But signature does not use overridden bucket but original bucket (the one set at instantiation) so it won't work for this use-case (as bucket can change dynamically).

**Comment by bikeath1337** [comment]
Thank you. That is because the 'bucket' key was removed from the override options (a relic from the initial branch), which was not correct. I pushed a commit to master which you can try out. Let me know and I will publish the fix.
