### ISSUE TITLE
SignatureDoesNotMatch error on HEAD request using AWS V4

### ISSUE THREAD

**Issue by dangerous** [TTLabs/EvaporateJS#185]
Everything else is working fine, but when I try to use the `allowS3ExistenceOptimization` option, I get a 403 from Amazon.  Inspection of the Amazon logs reveals that the problem is with the signature: `403 SignatureDoesNotMatch`.

**Comment by dangerous** [comment]
I've found the problem with this, I'll try and get a PR up today.

**Comment by bikeath1337** [comment]
Thanks much.

**Comment by bikeath1337** [comment]
@dangerous , v1.5.1 contains a fix that impacted S3 object names with paths (slashes). Just discovered today. See #196.

**Comment by dangerous** [comment]
@bikeath1337 I just saw this comment.  Actually I have come across a similar issue and your comment reminded me of it.  I just had a proper look at it and have submitted a PR https://github.com/TTLabs/EvaporateJS/pull/221 which will fix the so-far-unreported bug that uploads are broken for files with parentheses in their name.
