### ISSUE TITLE
Implementing a Test Framework

### ISSUE THREAD

**Issue by jakubzitny** [TTLabs/EvaporateJS#191]
Hey @bikeath1337, I am just comparing several libraries for uploading to S3 and this one seems to be by far the best fit. We're replacing our own little function that's sending HTTP requests directly. 

We're a bit sceptical about EvaporateJS, though, because you have no tests here. Is there any particular reason for that? Would you be interested in a PR with some test cases?

Thanks :)

**Comment by njbmartin** [comment]
Hey @jakubzitny, this is definitely something that @bikeath1337 has brought up before in another issue, but only a thought.

Let's turn this into a discussion about frameworks. The title seems a bit aggressive but I can appreciate a loss in translation. I would suggest amending the title to "Implementing a Test Framework" and opening this up to discussion.

**Comment by bikeath1337** [comment]
@jakubzitny , thanks so much for the vote of confidence. Since we added the MD5 checksums, the popularity of EvaporateJS increased a whole lot.

Yes, the lack of tests isn't good. Which test framework would you recommend and yes, if you've got a PR for us, I'd be glad to work with you.

**Comment by jakubzitny** [comment]
Thanks for quick replies and interest. I'd use `mocha` or `ava`, probably `ava`. Give me few days and I'll see if I can come up with a draft ;)

Just for comparison, this is how tests look like in "competitive" projects:
- [s3](https://github.com/andrewrk/node-s3-client/blob/master/test/test.js)
- [intimidate](https://github.com/jergason/intimidate/blob/master/test/index.js)
- [knox-mpu](https://github.com/nathanoehlman/knox-mpu/blob/master/test/multipart.js)
- [knox](https://github.com/Automattic/knox/tree/master/test)

**Comment by bikeath1337** [comment]
Thank yo, @jakubzitny , very much. Will take a look.

Was wondering what you thought of Tape? I was leaning to it for exploratory reasons but i have a lot more experience with Ruby's rspec that JS test frameworks.

**Comment by bikeath1337** [comment]
One of the reasons I enhanced EvaporateJS to support MD5 checksums was that I couldn't any JavaScript browser API product that supported it. AWS SDK for JavaScript only supported it for plain text mime types. I offered to implemented it for Amazon; they got back to me and then I let it drop due to other time pressures.

So i'm really wondering if anyone else found any open source solutions that actually the part checksum calculations cooperatively and effectively? That was the hardest part to solve when I did the work. Went down many dead ends that either were not CPU-cooperative or too memory intensive. I was astonished that I found no support for it.

Can you also tell me why you think EvaporateJS may be a good fit for you?

**Comment by jakubzitny** [comment]
Ava is [inspired](https://github.com/avajs/ava#why-not-mocha-tape-tap) by Tape, it's newer and runs tests concurrently with minimal config too. Tape should do allright as well though.

Not sure about the checksum stuff..

Evaporate seems to be the only JS lib that supports multi-part upload, retries and policy/signature auth, right?

**Comment by bikeath1337** [comment]
The multi-part upload is supported by all AWS S3 SDKs, including the browser SDK. They all support both signatures and their policies. The browser SDK, however, does not support checksums (except for plain text files!). So you can do multi-part uploads with retries but you can't be guaranteed that what you send is an exact copy of the original. That is the part that makes EvaporateJS stand out (and the part I am personally most proud of).

If you wonder how important the checksums are, I can assure you that if you are going to have a large customer base upload very large files (1GB or more), you can be confident it will happen often enough for you to want to prevent it. This is particularly important for video that you may want to transcode on the server. If your uploaded video isn't perfect and you use FFmpeg, it can hang the transcoder, make it fail, reduce quality or make the audio and video streams out of sync.
