### ISSUE TITLE
NPM version and bug in canonicalQueryStringV4

### ISSUE THREAD

**Issue by jessica-pixvana** [TTLabs/EvaporateJS#192]
NPM install returns version 1.4.6 which does not match this repo.

In 1.4.6 there is a bug in ```canonicalQueryStringV4()```

```javascript
searchParts = searchParts.length ? searchParts.split('&') : [],
searchParts = search.split('&'),
```

I think should be:
```javascript
searchParts = search.length ? search.split('&') : [],
```

**Comment by bikeath1337** [comment]
Thank you @jessica-pixvana . The NPM version was not correct. I republished it correctly at 1.4.7.
