### ISSUE TITLE
Running into CORS Issues

### ISSUE THREAD

**Issue by Masterdanielsan** [TTLabs/EvaporateJS#193]
Setup: I'm implementing EvaporateJS with the angular-evaporate project

Problem: My pre-flight requests are failing because of CORS error (Firefox):

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://s3.amazonaws.com/mybucket/1470681030091-Chrysanthemum.jpg?uploads. (Reason: CORS header 'Access-Control-Allow-Origin' missing)

I tried disabling CORS on Chrome with an extension and I got past the similar CORS error and notice that the OPTIONS request to the s3 bucket is returning 301 every time.

My Cors policy on my aws bucket is:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
    <CORSRule>
        <AllowedOrigin>*</AllowedOrigin>
        <AllowedMethod>GET</AllowedMethod>
        <AllowedMethod>POST</AllowedMethod>
        <AllowedMethod>PUT</AllowedMethod>
        <AllowedMethod>DELETE</AllowedMethod>
        <AllowedMethod>HEAD</AllowedMethod>
        <MaxAgeSeconds>43200</MaxAgeSeconds>
        <ExposeHeader>ETag</ExposeHeader>
        <AllowedHeader>*</AllowedHeader>
    </CORSRule>
</CORSConfiguration>
```
Any help would be appreciated immensely.  I'll post any additional info needed.

**Comment by bikeath1337** [comment]
This is not an EvaporateJS issue but one regarding configuration of your S3 bucket. The responses generated are outside of the bounds of EvaporateJS.

I did read that _perhapsI_ you might try specifying the AllowedOrigin as below (including the protocols), but according to the AWS S3 CORS docs, that shouldn't be necessary. 

```xml
<?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
    <CORSRule>
        <AllowedOrigin>https://*</AllowedOrigin>
        <AllowedOrigin>http://*</AllowedOrigin>
        <AllowedMethod>GET</AllowedMethod>
        <AllowedMethod>POST</AllowedMethod>
        <AllowedMethod>PUT</AllowedMethod>
        <AllowedMethod>DELETE</AllowedMethod>
        <AllowedMethod>HEAD</AllowedMethod>
        <MaxAgeSeconds>43200</MaxAgeSeconds>
        <ExposeHeader>ETag</ExposeHeader>
        <AllowedHeader>*</AllowedHeader>
    </CORSRule>
</CORSConfiguration>
```

**Comment by Masterdanielsan** [comment]
AFAICT the XML describing the CORS configuration is the only place to specify CORS access to a bucket... Could the request be malformed, causing s3 to give a funky response?  What would a proper OPTIONS request look like?  Should I have to add any headers manually or does the library handle that all?

**Comment by bikeath1337** [comment]
A library never handles CORS. The browser does and the library has no control over it. If you are getting CORS issues, the browser you are using is forming the request headers, sending them to the S3 URL and AWS S3 infrastructure is responding. EvaporateJS has no code related to this. You should not nor can you interact with this in any way. If you could, you would be able to circumvent the CORS security mechanism.

If you are running tests from a FILE opened in your browser, you cannot expect CORS to work. Make sure you are running your tests from a web server. For example, if local testing, make sure the run from a URL like so: 'http://localhost:300/example.html'.

Please make sure to re-enable CORS support on all your browsers.

Repeat: the browser adds CORS headers and enforces the server's response. AWS S3 is responding correctly.

My guess is you're running your tests from a file, not a web server. Your browser Url address probably looks something like this:

`file:///Users/user/EvaporateJS/example/evaporate_example.html`

If so, CORS can't be expected to work, so use a web server for your tests.

**Comment by Masterdanielsan** [comment]
I am serving the page from my server.  CORS is enabled on my browsers, but I do have an extension to turn it off on Chrome for testing... Only I run into the 301 response from s3.... 

I was asking if maybe the request has to be made with some header that would trigger AWS to respond differently.  For example, setting xhrWithCredentials:true adds a header I believe?  Using the angular-evaporate module, here are my settings:

'''
	$scope.evaConfigInit = {
	  bucket: '<redacted>',
	  aws_key: '<redacted>',
	  signerUrl: '/s3uploader/signer/',
	  awsRegion: 'us-west-2',
	  aws_url: 'https://s3.amazonaws.com',
	  logging: true,
	  maxConcurrentParts: 5,
	  retryBackoffPower: 2,
	  maxRetryBackoffSecs: 20,
	  partSize: 6 * 1024 * 1024,
	  awsSignatureVersion: '4', //if set to '4' then cryptoHexEncodedHash256/awsRegion  must be defined
//	  xhrWithCredentials:true,
	  computeContentMd5: true,
	  cryptoMd5Method:         function (data) { return AWS.util.crypto.md5(data, 'base64'); },
	  cryptoHexEncodedHash256: function (data) { return AWS.util.crypto.sha256(data, 'hex'); },
	  s3FileCacheHoursAgo: 12,
'''

Not sure if any of that is relevant.

**Comment by bikeath1337** [comment]
@Masterdanielsan , I have replied twice that there is nothing you can do about the headers. It is up to the browser you are using. EvaporateJS does not manage this and may not manage it at all.

I would put in a support ticket with AWS or with the angular-evaporate team.

**Comment by Masterdanielsan** [comment]
@bikeath1337 Thank you for replying twice.  I am sorry I did that to you.  I will follow your advice.

**Comment by Masterdanielsan** [comment]
Update, for what it's worth:
I had to change the aws_url from **https://s3.amazonaws.com** to **https://s3-us-west-2.amazonaws.com**
or else I get 301 responses and CORS errors.

Additionally, the **s3Acceleration** option doesn't seem to work out of the box for me either.
Any thoughts on this?

**Comment by bikeath1337** [comment]
I'm glad you were able to correctly configure your AWS options.

Regarding transfer acceleration, it doesn't work out of the box. You have to configure your S3 bucket per the AWS instructions. Follow the link on the the readme for instructions on how to configure your bucket when using the `s3Acceleration` option.

The AWS url currently will be set as follows (according the AWS directions) 

`https://bucketname.s3-accelerate.amazonaws.com`

**Comment by bikeath1337** [comment]
BTW @Masterdanielsan , you should keep you issues to one topic. The issues are browsed and searched by the community, so tacking on another issue is not good practice. If you still have questions about S3 transfer acceleration, please work first with AWS and then return with additional questions in a new issue. Thanks!

**Comment by Masterdanielsan** [comment]
@bikeath1337
Just to clarify:
> I'm glad you were able to correctly configure your AWS options.
I never said AWS options.  I was speaking specifically to the **aws_url** var in the EvaporateJS library.  I am speaking with an AWS representative tomorrow, so maybe it is a configuration issue, otherwise the EvaporateJS library is defaulting to https://s3.amazonaws.com.  I'm not sure that this works for everyone, and maybe the region should be automatically appended to the url as part of the library.  I'm not sure of the ramifications of doing so (again, this could be an issue specific to myself).

I only brought up acceleration because I know that that is another url pattern, and was wondering if that would snowball from the first issue. I'm trying to provide feedback that is related to the same issue.  I appreciate that you have a presence on this project, and have offered help.

**Comment by bikeath1337** [comment]
Evaporate allows you to specify your custom AWS_url if the default is not appropriate. This AWS configuration is what I was speaking to.

If you use he S3 transfer acceleration then the AWS irk cannot be configured as it just be the irk that AWS has currently published.

Please be kind and understand that I am a volunteer to help others with evaporateJS.

**Comment by Masterdanielsan** [comment]
I was only clarifying for others.  I do appreciate your help.

**Comment by bikeath1337** [comment]
I updated the readme to hopefully answer some of the questions you and others might have when they discover and learn about Evaporate.

**Comment by Masterdanielsan** [comment]
Hey, really good job!  The readme is much cleaner and more informative now. :)
