### ISSUE TITLE
cache-control And expires date

### ISSUE THREAD

**Issue by abunour22** [TTLabs/EvaporateJS#195]
Thanks for this library, Its Awesome . 

but i need to add cache-control And expires date to uploads !! 

I've tried xAmzHeadersAtInitiate but it doesn't work !!

**Comment by bikeath1337** [comment]
The readme includes references to this in the description for `notSignedHeadersAtInitiate`. Please give that a try.

**Comment by abunour22** [comment]
Awesome .. Thank you !!

**Comment by bikeath1337** [comment]
Any time. Please close the issue if you're all set.
