### ISSUE TITLE
I Cannot Upload Via Cloudfront

### ISSUE THREAD

**Issue by abunour22** [TTLabs/EvaporateJS#201]
There is a problem with cloudfront i don't know !! 

XMLHttpRequest cannot load https://s3.amazonaws.com/fd/profile/photos/avatar_562870015.jpg?uploads. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://mydoamin.com' is therefore not allowed access. The response had HTTP status code 403.

This is My Evaporate Options : 

            var options = {
                signerUrl: aws.signerUrl,
                aws_key: aws.key,
                bucket: aws.bucket,
                //aws_url: aws.url,
                s3Acceleration: false,
                cloudfront: true,
                allowS3ExistenceOptimization: false,
                maxFileSize: 5242880
            };
            ins = new Evaporate(options);

This is CROS For My Bucket !!

![vdvdsv](https://cloud.githubusercontent.com/assets/5248013/17643981/20a70d9a-6183-11e6-9f61-4c39f7c339ba.PNG)

This is Cloudfront Settings !!

![vcvcxv](https://cloud.githubusercontent.com/assets/5248013/17643991/608d2d9a-6183-11e6-95e8-60625abf9d6a.PNG)

What is missing !!

**Comment by bikeath1337** [comment]
The url ` https://s3.amazonaws.com/fd/profile/photos/avatar_562870015.jpg?uploads` does not agree with the url that Evaporate would generate with `cloudfront: true`. As this URL reads, the AWS bucket is `fd` and with the `cloudfront` option enabled,  the url would look like so:

`https://fd.s3.amazonaws.com/profile/photos/avatar_562870015.jpg?uploads`

The `cloudfront` option doesn't do anything but construct a url that you can use to configure cloudfront in front of S3.

**Comment by abunour22** [comment]
Great, Thanks :)
