### ISSUE TITLE
Suggestion: auto update region-specific endpoint for v4

### ISSUE THREAD

**Issue by Masterdanielsan** [TTLabs/EvaporateJS#202]
This came out of an issue I was having and overcame.  I recently spoke to AWS rep about it.
According the the AWS rep I spoke to, v4 won't* work when sent against the default url:

> s3.amazonaws.com

This being the case, and since there is a required variable "region" that gets set as part of v4 settings, I suggest that the aws_url is automatically updated to

> s3-**region**.amazonaws.com

when the region variable is specified in configuration settings.

*It might work if your data is saved on us-east-1 because 

> s3.amazonaws.com 

will resolve to 

>s3-us-east-1.amazonaws.com

on their end.  Still, in this situation, both urls would work, so the more specific one would be better.  

Anyways, just a suggestion and something that came up when I was setting up EvaporateJS and talking to AWS on the topic. :)

**Comment by bikeath1337** [comment]
Thank you. When I wrote the code for this, I used `s3.amazonaws.com` and everything worked.  That must be because I'm in US-EAST-1.
