### ISSUE TITLE
Setting custom header to signerUrl

### ISSUE THREAD

**Issue by joeyvmason** [TTLabs/EvaporateJS#203]
Is it possible to set a custom header (e.g. an auth token) for requests made to signer url. I'd like to be able to limit access to the signer url to logged in users.

**Comment by bikeath1337** [comment]
You should be able to use the `signHeaders` option when creating the Evaporate instance. These headers can be overridden for each file you `.add()`.

**Comment by jessica-pixvana** [comment]
I cannot seem to get this feature to work. It seems to ignore this parameter

**Comment by jessica-pixvana** [comment]
I think line 1283 should be changed from 
``` var signHeaders = makeSignParamsObject(me.signHeaders);``` to
``` var signHeaders = makeSignParamsObject(con.signHeaders);```

**Comment by joeyvmason** [comment]
Yeah it's not working for me either.

**Comment by joeyvmason** [comment]
@jessica-pixvana Yes it looks like `me.signParams` and `me.signHeaders` are used when probably `con.signParams` and `con.signHeaders` should be used.

**Comment by joeyvmason** [comment]
#204 fixes this.

**Comment by bikeath1337** [comment]
Thank you all
I will look at this tomorrow.

**Comment by AlexThomasWebElevate** [comment]
Any update on this? I am trying to send both signParams and signHeaders but neither of them work in version 1.5.2 and 1.5.3

**Comment by anoopdixith** [comment]
Hello, this is still not working for me. Any update in this?

**Comment by bikeath1337** [comment]
No known issues on this one. There is test coverage for it, as well. Refer to the previous note to your comment with "Sorry I realized what was wrong".
