### ISSUE TITLE
S3 Timeouts

### ISSUE THREAD

**Issue by joeyvmason** [TTLabs/EvaporateJS#206]
This is more of an S3 question than anything else, but has anyone else experienced 400 timeout errors when uploading to S3? Specifically, this is happening to users outside of North America, it's common for this to happen. It seems like the only options here are to adjust the timeout wait time on the AWS SDK and/or make the part size smaller. Unless it's possible to intelligently route users to the closest bucket to them?

**Comment by bikeath1337** [comment]
@joeyvmason I would ask Amazon if this is normal. I've not experienced it but I'm in North America. That's a pretty poor level of service on PUTs to S3!

I see you mentioned the AWS SDK timeout...but Evaporate doesn't use the AWS SDK, though you can make the part size smaller.

**Comment by bikeath1337** [comment]
Still having issues with this?
