### ISSUE TITLE
no element found

### ISSUE THREAD

**Issue by Masterdanielsan** [TTLabs/EvaporateJS#207]
I'm occasionally seeing 'no element found' in the dev tools console of Firefox, with a link like this:

**x no element found**            [cat_musketeer.jpg:1:1](https://avcs-upload-smithd.s3-accelerate.amazonaws.com/smithd/20160823.15%3A02%3A33/files/cat_musketeer.jpg?partNumber=1&uploadId=QS3BsyWsSgCrNPPt_7dOtG5Xgs0wPMlEQ.6GQpRbQOgH5rdslo8SVxB4gsQ.gpefkPmzv_MbgJNEuZNVnaB0IvpGr8ndzuQTnzhyJGClnwL_boTUZVq6euecF_p16Idx)

```
<Error><Code>MethodNotAllowed</Code><Message>The

 specified method is not allowed against this resource.</Message><Method>GET</Method><ResourceType>PART</ResourceType><RequestId>61124A42FDE984EB</RequestId><HostId>f70zk1V0yjsiF9M9SgDU6mUrWrukT5PT5zMK3HprI8d1ItCbyQmKTB3Upx/pJ5KJeR6+Jk1A0EQ=</HostId></Error>
```

Other than this, everything works fine.  All the network calls are 200s and the files are safely making their way up to the bucket as expected.

Any insight?

**Comment by bikeath1337** [comment]
Thank you. That probably means that the parsing logic doesn't know how to handle this AWS CORS reply. I will look into it.

**Comment by bikeath1337** [comment]
Are you working off of master?

**Comment by Masterdanielsan** [comment]
yeah. I should be using v1.5.1 since I updated after I ran into https://github.com/TTLabs/EvaporateJS/issues/196

**Comment by Masterdanielsan** [comment]
I opened a ticket with AWS and they are looking into it.  It didn't appear to be happening on Chrome, so they pointed me to this: https://bugzilla.mozilla.org/show_bug.cgi?id=884693

**Comment by bikeath1337** [comment]
I just created #211 which might help. Can you give it a try?

**Comment by Masterdanielsan** [comment]
The #211 changes in the getAwsResponse(xhr) function don't seem to be fixing the "no element found" bug.

**Comment by bikeath1337** [comment]
Great, that confirms what I suspected: 

1. there is a Firefox bug that is not ours to fix, as reported in the link you sent.
2. there was an issue in the XML parsing logic that broke IE. 

I will submit that PR in the next day or two.

**Comment by bikeath1337** [comment]
This appears to be an issue with firefox, not Evaporate.
