### ISSUE TITLE
Internet Explorer Compatability

### ISSUE THREAD

**Issue by Masterdanielsan** [TTLabs/EvaporateJS#208]
EvaporateJS seems to be bugging out on IE

![e_length](https://cloud.githubusercontent.com/assets/7672693/17939875/47c2115c-69e1-11e6-999f-765986f4c0a8.PNG)

**Comment by Masterdanielsan** [comment]
Possibly related, The request signature is not matching the one that AWS is getting when using IE.  I imagine that's because this is effecting the to_sign string.

**Comment by Masterdanielsan** [comment]
I changed that line to read 

>return (typeof code !== 'undefined') ? {code: code, msg: msg} : {};

and the debugger doesn't seem to be complaining anymore.  Uploads still seem to work on Chrome and Firefox, so this fix should probably go live.

IE still isn't sending valid signatures, however... should I open a new issue for this?

**Comment by bikeath1337** [comment]
Thanks for the report. It's important to reply with what OS and browser version you are using?

1. can you make sure that evaporate reports that the browser is supported?
2. I pushed #211 which could address the IE incompatibilities with innerHTML. Could you try it out?

**Comment by Masterdanielsan** [comment]
1. Windows 7 Pro.  Using Internet Explorer 11. Yes, **evaModel.supported** (angular-evaporate) is reporting true.
2. I'm not sure how to pull the file down on that branch, but I changed the three lines of code that changed.  Seems to fix #207 but doesn't seem to be doing anything for #208
