### ISSUE TITLE
Progress not decreasing after part failed

### ISSUE THREAD

**Issue by mario-areias** [TTLabs/EvaporateJS#209]
I am not quite familiar with the codebase, so please, feel free to close this if this is wrong. 

I am testing EvaporateJS for very slow connections, I was testing uploading one file, changed the `maxConcurrentParts`  to 1 and also changed my network throttling to upload as 50kb/s . Then I got a failure in one of my parts, but the progress value didn't decrease as specified on the `README` file.

This is how I instantiate the Evaporate Object:

```js
evaporate = new Evaporate({
            signerUrl: <redacted>,
            aws_key: <redacted>,
            bucket: <redacted>,
            aws_url: 'https://<redacted>.amazonaws.com',
            maxConcurrentParts: 1,
            s3Acceleration: true,
            s3FileCacheHoursAgo: 24,
            computeContentMd5: true,
            cryptoMd5Method: function (data) { return AWS.util.crypto.md5(data, 'base64'); },
            allowS3ExistenceOptimization: true
        });
```

These are the logs on Chrome console. I have redacted some info and added a space between the hash symbol and the number part so Github doesn't link this issue to any PR.

> making progress: **0.16125070817629383**
> redacted.s3-accelerate.amazonaws.com/481918de-d280-3696-7bee…QKoixvkGAvCjUn4Eh_yyOyPTTU3c5CdVcOg3fnMkAdoCEeyxxbr.EclDF.QThrKphQP0bQ--:1 PUT redacted..s3-accelerate.amazonaws.com/481918de-d280-3…PrQKoixvkGAvCjUn4Eh_yyOyPTTU3c5CdVcOg3fnMkAdoCEeyxxbr.EclDF.QThrKphQP0bQ-- net::ERR_CONNECTION_RESET
> redacted.s3-accelerate.amazonaws.com/481918de-d280-3696-7bee…QKoixvkGAvCjUn4Eh_yyOyPTTU3c5CdVcOg3fnMkAdoCEeyxxbr.EclDF.QThrKphQP0bQ--:1 PUT redacted.s3-accelerate.amazonaws.com/481918de-d280-3…PrQKoixvkGAvCjUn4Eh_yyOyPTTU3c5CdVcOg3fnMkAdoCEeyxxbr.EclDF.QThrKphQP0bQ-- net::ERR_CONNECTION_RESET
> evaporate.js:1329   ### 6291456
> evaporate.js:608 problem uploading part # 2,   http status: 0,   hasErrored: false,   part status: 2,   
> readyState: 4
> uploadPart # 3     will wait 250ms to try
> evaporate.js:1266 setupRequest() 
> problem uploading part # 2,   http status: 0,   hasErrored: true,   part status: 10,   readyState: 0,   isOnError
> UploaderController.js:68 making progress: 0.16125070817629383
> evaporate.js:1363 authorizedSend() upload # 3
> evaporate.js:1510 makeStringToSign (V2) PUT
> q6jWQEcMBlYERzDIbvkeHg==
> 
> 
> x-amz-date:Thu, 25 Aug 2016 03:22:05 GMT
> /<redacted>/481918de-d280-3696-7bee-2343f63c135f/redacted?partNumber=3&uploadId=sA8DswL7QOVjN_M7dzpDMO7Rqatf6ZsfBYbhG3r.6fBcyK3rdvntlzgo54jA1bApVNdMBeqEq6ykSCPrQKoixvkGAvCjUn4Eh_yyOyPTTU3c5CdVcOg3fnMkAdoCEeyxxbr.EclDF.QThrKphQP0bQ--
> evaporate.js:682 upload # 3 

> authorizedSend got signature for step: 'upload # 3'    sig: redacted
> evaporate.js:660 part # 3 (bytes 12582912 -> 18874368)  reported length: 6291456
> UploaderController.js:68 making progress: **0.16125070817629383**

**Comment by bikeath1337** [comment]
I pushed  PR #216 to address this. The part's bytes uploaded were not being reset the first time the part failed. On subsequent fails, the size was reset.

Does this address the issue for you, @mario-areias ?

**Comment by mario-areias** [comment]
Yes, it does. Thanks again @bikeath1337

**Comment by bikeath1337** [comment]
Thanks for the quick reply.
