### ISSUE TITLE
Documentation is incorrect: signParams and headerParams

### ISSUE THREAD

**Issue by tremby** [TTLabs/EvaporateJS#224]
The [documentation](https://github.com/TTLabs/EvaporateJS#evaporateadd) says that the `add` method's `config` argument can take `signParams` and `headerParams` options. This is inaccurate -- these are actually configuration parameters for the `Evaporate` constructor (and can also be passed to `add` in the *second* argument, the overrides for the Evaporate configuration). They should be moved up to the constructor configuration documentation.

Noticed as part of #219.

**Comment by bikeath1337** [comment]
Thanks @tremby . Actually, almost all of the options, except those documented as excluded, can be passed in that second object to `.add()`.

**Comment by tremby** [comment]
I'm aware -- that part of the documentation was clear enough!

**Comment by bikeath1337** [comment]
Thank you all for helping us improve Evaporate. Now that it seems to be getting traction in the community, it's great to see the collaboration.
