### ISSUE TITLE
Is it ok to put the AWS secret to the Lambda function in the client code?

### ISSUE THREAD

**Issue by davidascher** [TTLabs/EvaporateJS#233]
The tail end of the README describes how to use a lambda function to do the signing, but it needs an AWS secret (in the client code, IIUC).

```
var evaporate = new Evaporate({
    aws_key: 'your aws_key here',
    bucket: 'your s3 bucket name here',
    awsLambda:  new AWS.Lambda({
        'region': 'lambda region',
        'accessKeyId': 'a key that can invoke the lambda function',
        'secretAccessKey': 'the secret'
    }),
    awsLambdaFunction: 'arn:aws:lambda:...:function:cw-signer' // ARN of your lambda function
 });
```

Is that not a security no-no?  (If it's not, I suggest amending the README to explain why not)

**Comment by bikeath1337** [comment]
I'm not here to teach you what you already know, but stating the obvious, the part you refer to is skeleton code that needs to be completed. For node applications, the AWS data is stored in the environment and referenced.

The AWS Lambda contribution came from the community. As you are part of that community, I would appreciate your contribution to constructively correct it or clarify it, even if it means that AWS Lambda signing can't be used securely in this way. Thanks again @davidascher .

**Comment by davidascher** [comment]
I think my title may have been confusing.  I'm really just confused, and asking if that sample is correct because as I understand the Evaporate architecture that code (with values filled in for a particular instance) is in client code, which is generally visible to anyone (just need to visit the web app to see the source).  

I'll look at the source and try to figure it out, and report back. I suspect the `awsLambda`  bit is not needed, as the `awsLambdaFunction` should have access to whatever secrets are needed.

**Comment by bikeath1337** [comment]
The confusion is understandable. I would never put my secret in client code, either, if customers have a way of protecting their secrets through .env or the like, then that skeleton code is still useful. Any insight and help you can offer would be great. I could dig in a bunch more but I'm not well-read on lambdas and would defer to someone who is. Thanks again.

**Comment by bikeath1337** [comment]
@mcfedr could you help @davidascher with advice on how you deal with this? I think you were the driver behind this feature. Thanks!

**Comment by mcfedr** [comment]
The idea is that the key is in the client code, but the secret is only on the server side. You should think of it like a username and password situation, the key is your username.

This takes the same approach Amazon recommend in the samples for uploading to s3 directly from the client. 

The client code needs the key to be able to create the correct headers for the server to sign.

**Comment by mcfedr** [comment]
One moment. I have miss read slightly your question. It about invoking the Lambda function from JS.

This point is less clear, but I think its ok - If you make a specific IAM user that can only invoke that single lambda function.

Also note, since I add this function, AWS has added the API gateway service - it is possible attach a lambda function to an endpoint, and call it in this way, for this you use the normal signing url setting of evaporate.

**Comment by davidascher** [comment]
@mcfedr I believe I understand the architecture -- what I'm puzzled by is this line specifically in the README:

https://github.com/TTLabs/EvaporateJS/compare/master...davidascher:patch-1

(I'm still hoping to find time to dig into this codebase, just haven't yet).

**Comment by bikeath1337** [comment]
If it doesn't belong there, which I think we all agree on that one...either I or one of you can submit the PR unless you would like to assist posterity in explaining how to configure S3 IAM accounts. Thank you both for the quick replies!

**Comment by mcfedr** [comment]
The line from the README is correct and should stay. 

Please note this line:

> Setup an IAM user with permissions to call your lambda function. This user should be separate from the one that can upload to S3.

Its ok to put the key/secret for this user in the code as the only thing it can do is invoke that lambda function.

**Comment by davidascher** [comment]
Ah, I see.  So the point of the account is just to create a public endpoint for the lambda function.  I understand now your point about just using an API gateway.

**Comment by bikeath1337** [comment]
To keep things simple, coudln't we just give examples of how to use the newly-supported API gateway service for this purpose?

**Comment by bikeath1337** [comment]
Lambda functions in v2.0 would be supported through the pluggable signing feature. Built-in support has been removed to keep the code base more generic.
