### ISSUE TITLE
Add a method to get a FileUpload object by its ID

### ISSUE THREAD

**Issue by tremby** [TTLabs/EvaporateJS#235]
The documents mention a lot the `upload_id` which is passed to the various callbacks.

I needed to get at the data stored in `localStorage` for a given upload, and parsing it out of `localStorage` itself seemed like a chore.

I noticed through experimentation that `this` in the callbacks' context is a `FileUpload` object which has the data I need.

But is there any way to get at this outside of a callback?

A method to get this object from an `upload_id` might be useful.

**Comment by tremby** [comment]
In fact the `this` which comes back from the `started` callback is no good -- it has data as set up with the new attempt at the upload rather than the data from the original upload found in `localStorage`. The `this` which comes back from the `complete` callback has the correct (old) data. How can I go about getting that data as soon as it's available?

**Comment by tremby** [comment]
I wonder if the `me.started(me.id)` call in the `me.start` function should move down to the end of the function, so that by the time it is called `getUnfinishedFileUpload` has run, and so the data is correct?

**Comment by bikeath1337** [comment]
Well, if we ever expose the internal data, I think I would only want to do that with a copy of the EvaporateJS object.

What bits do you need to inspect?

**Comment by tremby** [comment]
What I needed to do was to detect if the upload was being resumed rather than started afresh.

This is because even if telling evaporate to add an upload to the queue and to upload it to a particular S3 key, if evaporate finds the same file in its localStorage and resumes it, it will not necessarily be uploading to the same key; it'll continue uploading to wherever it was originally trying to upload to.

For that reason, if it was being resumed I needed to retrieve the storage destination and pass it to my server with a later request. If it was being started afresh I didn't need to do this.

I found that as long as I waited a tick (`setTimeout(..., 0)`) the data in the `this` object had been updated and so I could grab the `signParams`. I stashed the key in here.

The timeout wouldn't have been necessary if you moved the `me.started(me.id)` call down to the end of the function, so that data has all been set up by the time the callback is fired.

And I wouldn't have had to throw this data in `signParams` if there were a way to retrieve the key being uploaded to when the `started` callback is fired.

**Comment by bikeath1337** [comment]
Thanks for clarifying. I think there is some confusion between the types of upload optimization Evaporate supports. If you already know this, please bear with me.

1. Resumption of an upload that has not completed.
2. Re-use of a completed  file on S3 if that file is identical to the local file. 

The former will _always_ use the object key of the multipart upload. The key will never change on resumption; either manually or through a browser refresh and then resubmission of the file.

The latter will report the object key uploaded (or found) on S3 as a parameter to the `complete` callback. This is the only instance that object key may be different from the object key specified when the file is added. You can compare the original to the returned value. BTW, this only happens with the S3 existence option enabled and if the file is found, the `complete` callback fires pretty much immediately. The existence feature will also only trigger if the file is uploaded to the same bucket as the previous upload that completed the file.

**Comment by tremby** [comment]
> The former will always use the object key of the multipart upload. The key will never change on resumption; either manually or through a browser refresh and then resubmission of the file.

This is what was a problem for my application. The client first tells my app that it wants to upload a file. I generate a UUID, and a storage key from that, and pass it back. I then attempt to start the upload with that key, and store it on the server side in session data so it can be associated with metadata the user is about to enter about the upload.

In the case where evaporate tries to resume an upload, it's no longer being saved to the key which I generated on the server side; it's being saved to another key I generated earlier. That's fine, and we can use the old one; I just need to know that key *before* the upload finishes, since the metadata about the upload will often be submitted to my server *before* the upload finishes.

> Re-use of a completed file on S3 if that file is identical to the local file.

I haven't actually explored what happens in my application in this case. I expect it's buggy if a user tries to do this...

**Comment by bikeath1337** [comment]
OK, that helps in understanding. 

Evaporate has to do some async work before it can know if the file exists or not, so before we can ask Evaporate for the object name, it needs time to find out what the name is. Until then, the object name is the one we requested.

This is why we can't solve this by polling for the object name or asking Evaporate to expose it...we have to wait until Evaporate knows it, otherwise, we'll be polling for the duration of an upload to a file that does NOT exist on S3.

The good news is that Evaporate will report IMMEDIATELY when it knows that the S3 object name is different than what we requested, avoiding the polling dilemma. The bad news is that the time to determine existence is probably very short, but still variable, so we'd still have to build in some arbitrary wait time before assuming we're dealing with a new uploaded file. Given how things work with S3, we can't work around the async nature of it.

Additionally...
...I think we we could listen to the AJAX calls and as soon as we sniffed the POST request to create a multi-part upload, we'd have our answer.

Or...we could add a new callback like `initiated()` that Evaporate invokes when it starts a new upload with the requested object name.

FWIW, with checksums enabled, the flow for completed file existence goes like so:

1. The `started()` callback fires before trying to find the local file in localStorage. 
2. If found, it is considered completed on S3 if the eTag exists
1. re-calculate first part's checksum (_Async_ using the FileReader API)
2. After checksum is calculated, check S3 for existence (_Async_ HEAD request )
3. If the file exists, the `complete()` callback is immediately fired with the S3 object name.
4. If the file doesn't exist, then a new multi-part upload is initiated and

**Comment by tremby** [comment]
It looks like your last comment wasn't complete -- you ended with "and".

Are you saying that my workaround of checking the data after a timeout of 0ms will not work in all cases? It's been fine for everything I've tested so far. We'd get the same result (for what it's worth) with my suggestion of calling the callback slightly later.

If I understand you correctly you're saying, however, that there will be some cases where it's not good enough and you don't know for sure where you're uploading to until some unpredictable amount of time has passed. That's fine with me -- such a callback would be useful. The user is unlikely in my case to enter all the upload metadata in less than a few seconds, for example.

**Comment by bikeath1337** [comment]
Thanks, Bart. I just completed the line with "and its parts will be uploaded."

To summarize, there is no workaround with a 0 timeout given the asynchronous design of XHRs. We need to ask S3 if the file exists and do our best to make sure that the file-to-be-uploaded is the same. That takes time and Evaporate doesn't do anything to get in the way or delay the response via the complete callback.

**Comment by tremby** [comment]
> there is no workaround with a 0 timeout given the asynchronous design of XHRs

In my test cases, the value I'm grabbing for the upload destination and `signerParams` (from `this`) is "incorrect" for my purposes in the `started` callback but "correct" after a 0 timeout started in that same callback. Are we talking about the same thing?

**Comment by tremby** [comment]
To (hopefully) clarify, I do understand if you're saying that I won't have the right answer in certain circumstances. I think this is why you suggested a new `initialized` callback above, which would happen at some point after `started` and before `complete`.

**Comment by bikeath1337** [comment]
I am not suggesting anything new because we already have a callback that provides what you need to known when Evaporate re-uses an S3 object.

**Comment by tremby** [comment]
I must be missing something. You said:

> Or...we could add a new callback like `initiated()` that Evaporate invokes when it starts a new upload with the requested object name.

Now you say there's already one. Which do you mean, `completed`? What I need is the S3 key or `signParams` corresponding to where the file is being uploaded to (or has been uploaded to). Is there a single callback I can use to get this in any circumstances, as soon as it is available?

**Comment by bikeath1337** [comment]
Sorry about the confusion. The callback exists and it is the complete callback. I'm copying the bit from the readme that documents it:

* **complete**: _function(xhr, awsObjectKey)_. a function that will be called when the file upload is complete.
    Version 1.0.0 introduced the `awsObjectKey` parameter to notify the client of the S3 object key that was used if
    the object already exists on S3.

**Comment by tremby** [comment]
OK, but this happens much too late in most circumstances for my use case.

In my use case, the user starts uploading a video file (which could be very large -- biggest we've had so far is just shy of 20G) and then starts adding metadata. I need to know the location the video is being uploaded to by the time the user submits the metadata, whether the upload has finished by then or not.

That means the `complete` callback will have fired if the video was small (and totally uploaded already), was continued and then completed already, or was already finished. It will not have fired if the video was fresh and has not finished uploading yet, or continued and has not finished uploading yet. In those cases I need to know where it's being uploaded to before `complete` fires.

**Comment by bikeath1337** [comment]
I do not want to beat a dead horse. There is no free lunch. Evaporate has to calculate the checksum of the first chunk and submit a HEAD to AWS for the object. Most likely, the most costly portion of this work will be the checksum work. In my case, with a 6MB part size, I get the response within 1 - 2 seconds. The time-cost is dependent on the chunk size--not the file size--and the round-trip HEAD request.

**Comment by tremby** [comment]
I understand that. 1 to 2 seconds is fine. So how can I get that information of where we're uploading to after those 1 to 2 seconds once it's known to Evaporate? That's my question.

**Comment by bikeath1337** [comment]
The complete callback includes it in the second parameter.

**Comment by tremby** [comment]
But doesn't `complete` only fire once the entire upload has finished? Doesn't Evaporate know where it's uploading to long before that in many cases (such as a file of 20 chunks being continued from chunk 3)?

**Comment by bikeath1337** [comment]
I have said repeatedly that the complete callback fires as soon as evaporate knows that the file is already on S3. I cannot add any more to the conversation.

**Comment by tremby** [comment]
I'm sorry for the frustration, but I don't know where the disconnect is here. It seems to me that you're not reading my messages, but it could be that I'm not understanding something fundamental.

What does "already on S3" mean? To me that means the file has completed uploading. I know that I can get this information when the file has completed uploading. If this happens when it is found that the file has *already* finished uploading, or if the upload finishes while my user is still entering metadata, that's fine.

But as far as I can tell you continue not to address the other possibility I'm raising, that the file has *not* yet finished uploading. As in the example I gave above, what about a file which Evaporate finds is partially uploaded at add time, and begins to continue uploading it? What is the soonest in this case I can get the upload destination? If `complete` won't fire until it finishes, this is too late for me.

**Comment by bikeath1337** [comment]
I did answer both cases. Here is the comment with highlights to both use-cases:

1. Resumption of an upload that has not completed.
2. Re-use of a completed  file on S3 if that file is identical to the local file. 

The former **(1. resumption of incomplete)** will _always_ use the object key of the multipart upload. The **key will never change on resumption**; either manually or through a browser refresh and then resubmission of the file.

The latter **(2. the file has already been fully uploaded to S3 by the same uploading browser)** will report the object key uploaded (or found) on S3 as a parameter to the `complete` callback. **This is the only instance that object key may be different from the object key specified when the file is added.** You can compare the original to the returned value. BTW, this only happens with the S3 existence option enabled and if the file is found, the `complete` callback fires pretty much immediately. The existence feature will also only trigger if the file is uploaded to the same bucket as the previous upload that completed the file.


The latter will report the object key uploaded (or found) on S3 as a parameter to the complete callback. This is the only instance that object key may be different from the object key specified when the file is added. You can compare the original to the returned value. BTW, this only happens with the S3 existence option enabled and if the file is found, the complete callback fires pretty much immediately. The existence feature will also only trigger if the file is uploaded to the same bucket as the previous upload that completed the file.

**Comment by tremby** [comment]
> The former (1. resumption of incomplete) will always use the object key of the multipart upload. The key will never change on resumption; either manually or through a browser refresh and then resubmission of the file.

I am aware of this but need a way to get that original key. I think perhaps this is where we are not seeing eye to eye.

When I run `add()` I am using a randomly-generated key `abc` from my application server. If the user stops and comes back in a different browser session and chooses the same file again, I am now using a different randomly-generated key `xyz`. Evaporate correctly finds that it has already started uploading this file and continues with the *original* randomly-generated key `abc`. I need a way to get this original key `abc`, when Evaporate discovers it, as soon as possible. This is what I achieve with that 0ms timeout, but you seemed to be saying this is not good enough.

> The latter (2. the file has already been fully uploaded to S3 by the same uploading browser)

I have no problems here; I can get the data from the `complete` callback in this case as you point out.

**Comment by bikeath1337** [comment]
The retry and re-use scenarios are solved by a single simple callback.

Until Evaporate responds with the complete callback, any file uploaded to S3 _is in an indeterminate state_ from the server perspective: it’s either fully uploaded (visible) OR is incomplete (not visible) OR is deleted (not visible).

Until _Evaporate tells you that an upload completes, anything you decided with the object key is conjecture_. You can only tell your server side logic what definitively to do after the complete callback. There are no exceptions.

In all use cases described above, Evaporate attempts to give you tools to complete uploads with the greatest efficiency (translate: invoke the complete callback).

FWIW this is how one client manages the flow using Evaporate. Their flow is more complex than this description but the logic still applies:

1. Server is notified that an upload starts for informational purposes only. It’s informational only because of what I’ve described above.
2. Upload completes. Server is notified of the definitive object name of the user’s uploaded file. That object name can and should be expected to be different than the “informational” object name.  Processing of this S3 object kicks off using the definitive object name.

The retry and reuse scenarios are solved by a single simple solution.

If you require some processing of a partially uploaded file, I wouldn’t know how to achieve it.

Without any enhancements to Evaporate, you can, however, use the informational object key to report against the competed object keys to gain some insight into how many uploads are initialized but not complete — but you cannot gain insight from this report as to why the uploads did not complete.

**Comment by tremby** [comment]
I know the complete file doesn't exist until the upload completes. All I want is to know and store on the server side while the upload is still in progress is where later to *expect* it to be.

You talk about an informational vs definitive object name. I think what I'm not understanding here is how Evaporate can continue and complete an upload if it's not sure which object key it's uploading to. From a look at the code it certainly seems to know (at least after the first few calls to AWS to see what the status of the file is) -- all of the calls to AWS use `getPath()` as part of their path, which contains the object key (from `me.name`). Maybe there's some crazy edge case where the real final value doesn't match what is here, but that doesn't bother me. I want a best guess.

Indeed, the object key passed with the `complete` callback is just the value of `me.name`. As far as I can tell that hasn't been modified since after the file upload status checks.

What am I missing? All I want is to get the value of `me.name` once it's (at least probably) no longer going to change again.

**Comment by bikeath1337** [comment]
If evaporate uses the existing object key name on S3 and does not report that keyname through the complete callback, and the requested key name is different, then that is a bug.

From my experience, claiming "probably not going to happen..." is a wishful thinking, particularly in the inherently chaotic world of the internet. For example, if a customer suffers from low bandwidth (due to some chaotic situation out of your control), they may actually retry several times and it can be expected that more and more parts will be added to S3 as a result. Each time they do this, the requested AWS key will differ than what is on  S3 and this can be expected to happen many times, in spite of all our good intentions, hopes or aspirations.

I manually tested Evaporate just now. The code creates a random key for the same file and then after a few parts uploaded, I refreshed the browser, re-selected the file and submitted it. The result is shown here from the temporary console logs I added:

```
Starting upload for awsKey: **830105685_chandelier-264.mp4**
Navigated to http://localhost/~bobbywallace/EvaporateJS/example/evaporate_example.html
Starting upload for awsKey: 488912795_chandelier-264.mp4
Navigated to http://localhost/~bobbywallace/EvaporateJS/example/evaporate_example.html
Starting upload for awsKey: 588915266_chandelier-264.mp4
Complete: Requested key: 588915266_chandelier-264.mp4 -- S3 key: **830105685_chandelier-264.mp4**
```

**Comment by tremby** [comment]
I think once again we're talking at cross purposes.

The key coming back with the `complete` callback comes from the `name` property of the `FileUpload` object by way of the `getPath` method. This is correct. No bug here as far as I can tell.

From looking at the source code, it looks like this `name` property is set only twice:

1. The `add` method
2. The `getUnfinishedFileUpload` method

The first one is obvious, and that's where it's set, in your example, to `830105685_chandelier-264.mp4` the first time, then `488912795_chandelier-264.mp4` the second time, then `588915266_chandelier-264.mp4` the third time.

The second one is from a *synchronous* call to `getUnfinishedFileUpload` during the `start` method, *synchronously after* the `started` callback is called. This is when Evaporate resets the key to `830105685_chandelier-264.mp4`, which it has found from `localStorage` because it is attempting to continue an existing upload.

This is the value I want, and I want it *as soon as possible* (in the case of a long upload, long before `complete` is fired). As far as I can tell I'm doing exactly the right thing by waiting for the next tick from the `started` callback and then querying `this` (the `FileUpload` object) for its `name` property. By this time the `start` function has completed, `getUnfinishedFileUpload` has run and reset the `name` property, if appropriate.

My suggestion was to move the `me.started(me.id)` call to later in the `start` method (to the end perhaps) so that I don't have to use a timer like this. But you have been suggesting I cannot rely on the `name` property at this point and I need to wait for the `complete` callback. I don't see how that's true, given that `name` is never changed after this point (only in the above two cases, which are earlier), and so I don't see how `complete` could ever report something different.

**Comment by bikeath1337** [comment]
Thank you for the suggestion. Unfortunately you are describing private methods that you would like to bend to your own ends. If you want to customize Evaporate for that purpose, please feel free to fork the project and deploy from your own code.

**Comment by tremby** [comment]
I fail to see how my use case counts as bending Evaporate to my own ends.

Do you understand my use case? Does it really not seem useful to you to be able to get the "corrected" S3 key from Evaporate as soon as it has been determined, rather than having to wait for the `complete` callback (which in some cases could be hours)?

If you don't like the idea of user-side code accessing the `FileUpload` object, that's fine. But for users who *do* want to do that, it would be helpful if that `started` callback were fired just a little bit later. (It does say `started` in the past tense, rather than `starting`, and is currently called near the beginning of the the `start` method, so one could argue its current naming with respect to when it is called is confusing.) What do you have against doing this?

If you have some reason that you don't want to do that, what about adding a new callback at the end of `start` which gives as an argument the S3 key? You suggested in a previous comment adding a new callback.

Or if a new callback seems superfluous (I think it is), what about moving the `started` callback as suggested before but not making a user dig into the `FileUpload` object by passing an extra argument to it containing the S3 key?

**Comment by tremby** [comment]
If you really don't want users digging in to `FileUpload`, by the way, perhaps consider not making it the context of the callbacks.

**Comment by bikeath1337** [comment]
FWIW, I published `r2.0.0-rc.1` for anyone who wants to give it a spin. It doesn't include this feature but is intended to be a big improvement on the existing, with easier upgrade paths to more features.

**Comment by bikeath1337** [comment]
`v2.0.0-rc.4` adds a new callback `nameChanged` to handle two use cases, both of which only apply if a randomized AWS object key is used to avoid namespace clashes when multiple users are uploading to the same bucket. The record of uploaded file name and it's multipart upload ID is stored in localStorage on the user's browser.

## Interrupted Uploads

This optimization is only enabled with the following configuration options:

`s3FileCacheHoursAgo: 24` -- cache must be enabled to some desired value

1. User starts upload of file `video1.mpg`
2. Evaporate configuration assigns randomized S3 object key name `0a34d` and creates a multipart upload on AWS for that object. 
3. User refreshes browser page. 
4. User re-uploads `video1.mpg`
5. Evaporate configuration assigns randomized S3 object key name `dfc23`.
6. Evaporate determines that `video1.mpg` was part of an interrupted upload. 
7. Evaporate invokes `nameChanged` with the AWS object key used (`0a34d`) when the interrupted upload was created.
8.  Evaporate resumes the interrupted upload until completed or canceled.

## Object Reuse Optimization
User uploads many very large video files with the purpose of having them processed as a single unit, for example, for file stitching. In this use case, the stitching cannot complete until all files are uploaded.

If even _one_ of the files fails, without the existence optimization, the user must _re-upload all_ of the files again. With the existence optimization, when the user uploads all of the files again, then only those files incomplete files are uploaded. Any files that already are complete are not uploaded again.

This optimization is only enabled with the following configuration options:

`s3FileCacheHoursAgo: 24` -- cache must be enabled to some desired value
`allowS3ExistenceOptimization: true`
`computeContentMd5: true`
 
Evaporate will invoke `nameChanged` with the S3 object key of the fully-uploaded file on S3 for each file that can be re-used.

**Comment by tremby** [comment]
What do you mean by randomized AWS object keys? Is this some option Evaporate offers? In my case, my back-end server decides on an object key, and I then feed this to Evaporate. So does the above apply in my case?

**Comment by tremby** [comment]
Oh, on reading again (and reading the email you sent me) I think I understand that by a "randomized AWS object key" you mean an object key specified at "add" time, rather than just using whatever the name of the user-selected file was. In this case -- great -- this callback should do exactly what I needed.

I'm confident that what you're saying is now there is what I needed so as far as I'm concerned this can be closed.

Thanks! I hope to be working on a project again soon which needs tech like this, so that I can give it a shot.

**Comment by bikeath1337** [comment]
Evaporate 2.0 will include the "nameChanged" callback which Evaporate will invoke immediately when it re-uses a previous upload on S3, complete or incomplete.

**Comment by tremby** [comment]
Sounds perfect. Thanks.
