### ISSUE TITLE
How does Evaporate handle maxFileSize?

### ISSUE THREAD

**Issue by alvinwoon** [TTLabs/EvaporateJS#245]
As far as I can test, no error or warning message is returned when user uploads file that exceeds the limit.

**Comment by bikeath1337** [comment]
Don't shoot the messenger but the add() method returns the file_id or an error message. If the return value is an Integer, you've got a file_id, if it's a String, you've got an error message. The docs should be updated to explain that.

**Comment by alvinwoon** [comment]
@bikeath1337 thanks!
