### ISSUE TITLE
Occasional *Random* 403 Signature does not match and 400 bad request

### ISSUE THREAD

**Issue by GitJaap** [TTLabs/EvaporateJS#249]
I've started using evaporate and it's exactly what I needed! I do run into some issues. I just tried uploading a 3gb file and i recieved occasional 403 responses on parts which then retried and were successfull. Is this expected behaviour or can it be due to my server signing protocol?. 

Eventually nearly all parts completed, but just before completion it got 3 bad request messages. 
`<Error>
<Code>InvalidPart</Code>
<Message>One or more of the specified parts could not be found.  The part may not have been uploaded, or the specified entity tag may not match the part's entity tag.</Message>
<UploadId>USFnqSdv0Kx2V71kk9bRItyGEeOPTZ46WNkRjNfKuvBjlfx2X8Dqww7uQfZnNu8q8oQWJRvz5gaflYw9XmIHOg--</UploadId>
<PartNumber>485</PartNumber>
<ETag />
<RequestId>233EE6B0546A5AD5</RequestId>
<HostId>+scrNVdSJj92H4u+caYWNWv05BSZd0FpSgi4TMW/3xDudfHJG29i1PaszXsZ7GNyCNs1/aAn1tI=</HostId>
</Error>`

Now the partmonitor just keeps on running but evaporate has launched the onError event.
![image](https://cloud.githubusercontent.com/assets/8937555/18614899/2ca67532-7d98-11e6-882d-f179a84f39f9.png)

My setup:
php server side signing of AWS v4 requests. I do have multiple instances of evaporate running at the same time(3 file upload buttons), but for small files this gives no problem.

Any ideas on how I can improve reliability? My signing snippet is just 
` 
        $to_sign = Input::get('to_sign');

        $kSecret = 'AWS4' . Config::get('app.amazon.secretkey');
        $alg = 'AWS4-HMAC-SHA256';
        $region = S3::getRegion($track->getDiskName());
        $service = 's3';

        $alg = substr(strtolower($alg), strlen('AWS4-HMAC-'));    // trim 'aws4-hmac-'
        $kDate = hash_hmac($alg, Carbon::now()->format('Ymd'), $kSecret, true);    //UTC time
        $kRegion = hash_hmac($alg, $region, $kDate, true);
        $kService = hash_hmac($alg, $service, $kRegion, true);
        $kSigning = hash_hmac($alg, 'aws4_request', $kService, true);       
        $signature = hash_hmac($alg, $to_sign, $kSigning);      

        $response = Response::make($signature, 200);
        $response->header('Content-Type', 'text/HTML');`

**Comment by bikeath1337** [comment]
Hi, @GitJaap , these are known issues and should be fixed in #248. I'm working on wrapping it up now. It will be released as 1.5.7. When released, let me know if the uploads are reliable.

**Comment by GitJaap** [comment]
@bikeath1337 thanks for the quick response and good to hear! If you need more data-dumps or logs let me know.

**Comment by bikeath1337** [comment]
Thanks much. Don't need any more information other than feedback on the new branch. It took some time but the issue was clear and reproducible. Ik ben blij dat je Evaporate nuttig vind!

**Comment by GitJaap** [comment]
Haha, thanks for the update. The errors on completion are solved now and all uploads successfully complete !

But I still have about 30 AWS signature does not match and 40 Err:connection reset errors while uploading 50 parts of 6mb(total 314mb). This has quite an impact in performance( it seems that on average each of the parts need atleast one retry), although I uploaded 314 mb in around 5minutes, which is about 1mb per sec and indeed around half of my max upload speed(15mbit / sec). Is this normal behaviour for large file uploads or is there still something else going wrong?

**Comment by GitJaap** [comment]
I changed the upload particle size to 30mb per particle and got rid of the issue. Works like a charm now, thanks for your quick help today @bikeath1337

**Comment by bikeath1337** [comment]
@GitJaap What was your part size originally? The part size should have nothing to do with it unless, I suppose, your part size were smaller than the AWS minimum part size. I want to make sure we're not missing an edge case.

FWIW, an AWS support rep once told me that the optional part size was 72MB. He couldn't tell me why, thought. I believe that the part size should be sized based on the speed of the pipeline, but I don't know of a way to do that dynamically. The smaller the part, the greater the overhead but also the easier in which a part can be retried on error.

**Comment by GitJaap** [comment]
@bikeath1337 My part size was the default size(6mb i think), so it was indeed strange that so many error occured as the minimum AWS part size is specified as 5mb.

**Comment by diogobeda** [comment]
>  Either your signature method is not correct, perhaps you're not using the provided datetime parameter...or you're not using the 1.57...or there is another issue to solve.

@bikeath1337 I'm using `2.1.0` and also using the `datetime` param from the server on the signing algorithm, but still seeing this error for around 50% of the time on a 260kb file. Do you have any tips for me?

**Comment by bikeath1337** [comment]
@diogobeda if you see signature mismatch errors from Amazon, then you need to compare what Amazon uses to calculate the signature against what Evaporate was doing. At this point, based on the growing user base, it might be safe to claim that Evaporate is stable in that regard. In 2.1.1, released today, we fixed a file naming issue that resulted in a signature mismatch; however that has nothing to do with random errors.

If you enable debug in Evaporate, it will render the elements it uses to create the signature. You need to compare these to what AWS uses (they return it in the XML response with the error).

**Comment by offner** [comment]
@diogobeda If you have multiple instances behind a load balancer signing requests, ensure you aren't signing uploads with two different keys.
