### ISSUE TITLE
Upload stuck after getPayloadSha256Content

### ISSUE THREAD

**Issue by gpsamson** [TTLabs/EvaporateJS#263]
When a file is added, EvaporateJS gets stuck at getPayloadSha256Content and continues to log monitorPartsProgress. I checked the network and EvaporateJS makes a call to list the uploaded parts, but doesn't attempt to upload anything new. Any ideas for a fix? Thanks!

<pre><code>add 
 processQueue   length: 1
 starting FileUpload 0
 onFileUploadStatusChange
 processQueue   length: 1
 getUploadParts() for uploadId starting at part # 0
 setupRequest() Object {method: "GET", path: "/abc123/19ECUhBuX4tbtD7Heb6TUnli/a…6MR0R9AK_Fn0gZGkaaP_hkMr5Nkz&part-number-marker=0", query_string: "&part-number-marker=0", x_amz_headers: null, step: "get upload parts"}
 authorizedSend() get upload parts
 getPayloadSha256Content e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
 CanonicalRequest (V4) GET
/abc123/19ECUhBuX4tbtD7Heb6TUnli/artwork.jpg
part-number-marker=0&uploadId=HnnaMncR2btIAE4j3J8xhuV0KV_GL9SZ4MChVcY678Wv23IsaRlkQFj9t2Fz.hoWXTrgplkdb0sCDLwFmnQfNVOz4GqEq0QvwSmK6MR0R9AK_Fn0gZGkaaP_hkMr5Nkz
host:s3-us-west-1.amazonaws.com
x-amz-date:20161110T074258Z

host;x-amz-date
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
 makeStringToSign (V4) AWS4-HMAC-SHA256
20161110T074258Z
20161110/us-west-1/s3/aws4_request
ffc9844373299046a4af720c5993168c62b580f15b3af4d1245c1168b692a902
 authorizedSend got signature for: get upload parts - signature: ec1183d55c1bf41a6621d5f3a81f6d0a7bb1663e311a3b69d82048311ef9e701
 getPayloadSha256Content e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
15 monitorPartsProgress()</code></pre>

**Comment by bikeath1337** [comment]
1. Are you trying to use Evaporate for the first time?
2. How are you instantiating Evaporate?
3. How are you adding the file?
4. What version are you using?

The way you describe it, you're trying to restart an incomplete upload. In a normal use-case this would happen if you refreshed your browser after the multipart upload is created but before the upload completes all the parts. This is the use-case for triggering the list part path.

You should first verify that you can get a file to upload. To clear the cache that keeps track of uploaded parts, execute this in the console:

```
delete localStorage.awsUploads
```

Refresh the browser and try to upload the file. you should see a POST (init), PUTs and a final POST (complete). Please reply with the answers and we'll go from there.

**Comment by bikeath1337** [comment]
@gpsamson is this still an issue or did you define the method and were able to move on?

**Comment by gpsamson** [comment]
It was an issue with a browser extension. Cheers for the follow up!
