### ISSUE TITLE
Single Quote in File Names Breaks signature Calculations

### ISSUE THREAD

**Issue by bikeath1337** [TTLabs/EvaporateJS#264]
A single quote should be encoded in an S3 object name. Without proper encoding, the signature fails.

**Comment by profsmallpine** [comment]
@bikeath1337 Since this is missing `g`, it will only replace the first instance of a single quote. With a filename including two single quotes, it will fail as the second single quote is not replaced. Was this on purpose? I noticed both the previous replace calls include `g`.

**Comment by bikeath1337** [comment]
Thank you. That needs to be addressed. Feel free to submit the fix as PR.
