### ISSUE TITLE
Getting 'Failed' when adding evaporate into WebJars

### ISSUE THREAD

**Issue by marekliptak** [TTLabs/EvaporateJS#268]
Hi,
we use WebJars - http://www.webjars.org/ in our project and we would like to start using angular-evaporate and EvaporateJS through WebJars as well. I tried to deploy angular-evaporate 2.2.1 as a new NPM WebJar at http://www.webjars.org/npm and that was successful. But when I tried to build my project using Gradle, I got error that it needs of course also evaporate 1.5.2 as dependency. Therefore I tried to deploy also evaporate 1.5.2 as a new NPM WebJar but got the following error, I got also the same error when I tried to deploy latest 1.6.2:

> Failed!
> All attempts to determine an acceptable license have been exhausted. The package.json file did not contain a spec-compliant license definition and the license could not be determined by trolling through the source repo: https://github.com/TTLabs/EvaporateJS
> The acceptable open source software licenses are at: https://bintray.com/docs/api/#_footnote_1
> The provided licenses were: BSD-2-Clause
> This problem will likely need to be resolved by working with the library maintainers directly.
> If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues
> 
> Got NPM info
> Determined Artifact Name: evaporate
> Starting Deploy

My only guess is that it could be because of that:

`"license": "BSD-2-Clause"`

which you have in package.json - https://github.com/TTLabs/EvaporateJS/blob/1.6.2/package.json.

Maybe it should be without that first hyphen, because that is what I see in their recommended link https://bintray.com/docs/api/#_footnote_1 at the bottom: **BSD 2-Clause**.
Thank you.

Marek

**Comment by bikeath1337** [comment]
Hi, @mareklip, thanks for the report and for using Evaporate. FWIW, you should be using v1.6.2 rather than 1.5.2, as it is the most stable version.

I would be more than happy to review and eventually accept a PR for the change you need if you would like to submit one. You seem to be in the best position to test any changes out.

**Comment by marekliptak** [comment]
Hi @bikeath1337,
yes, I am going to use 1.6.2 or now newer after PR, I was just talking about 1.5.2 because that was mentioned in that dependency error I was getting from angular-evaporate.

I fixed that license, please check the [PR](https://github.com/TTLabs/EvaporateJS/pull/271). I also tested it by deploying it as 1.6.3. to WebJars from my forked EvaporateJS repository and deployment is now working fine without above error:

> Deployed!
> It will take a few hours for the Maven Central index to update but you should be able to start using the NPM WebJar now.
> GroupID = org.webjars.npm
> ArtifactID = github-com-marekliptak-EvaporateJS
> Version = 1.6.2
> 
> Synced With Maven Central
> Published BinTray Version
> Signed BinTray Assets
> Published BinTray Assets
> Created BinTray Version
> Created BinTray Package
> Created NPM WebJar
> Fetched NPM tgz
> Generated POM
> Converted dependencies to Maven
> Resolved Licenses
> Got NPM info
> Determined Artifact Name: github-com-marekliptak-EvaporateJS
> Starting Deploy

Only I think you will have to do those version changes in your files as you know better after accepting PR, so that it is changed from 1.6.2 to 1.6.3, because webjars determined that fork as 1.6.2 since I did just the fix without version changes. Thanks.

Marek

**Comment by bikeath1337** [comment]
#271 merged to master and will be in the upcoming release.

**Comment by bikeath1337** [comment]
Your change is in 1.6.3, just published! @marekliptak
