### ISSUE TITLE
EvaporateJS doesn't compute part MD5, which causes signing to fail

### ISSUE THREAD

**Issue by YMIndustries** [TTLabs/EvaporateJS#272]
Hi,

I'm just getting started with EvaporateJS (I'm actually using Angular-Evaporate) and I've hit a problem. When I try to upload a file, I get an error from Amazon saying:

    SignatureDoesNotMatch
    The request signature we calculated does not match the signature you provided. Check your key and signing method.

Inspecting my request to my signer endpoint, I can see that the text Evaporate is trying to get signed is:

```
POST

video/mp4

x-amz-date:Mon, 28 Nov 2016 06:42:54 GMT
/my-bucket/test.mp4?uploads
```

According to the [AWS documentation](http://docs.aws.amazon.com/AmazonS3/latest/dev/RESTAuthentication.html#ConstructingTheAuthenticationHeader), the second line should contain the md5 hash of the part, and the fourth line should contain the date. Both of these are empty.

My config looks like this:

```
$scope.ae = new AngularEvaporate({
	computeContentMd5: true,
	cryptoMd5Method: function (data) { return btoa(SparkMD5.ArrayBuffer.hash(data, true)); },
	aws_url: "https://s3-ap-southeast-2.amazonaws.com",
	aws_key: "MYKEY",
	signerUrl: "MYSIGNINGURL",
	bucket: "my-bucket"
});
```

My signing Lambda function looks like this (use of Lambda is temporary, so I'm using signerUrl instead of the special lambda things):

```
var crypto = require('crypto');

exports.handler = (event, context, callback) => {
    callback(null, {
        statusCode: 200,
        headers: {
            "Access-Control-Allow-Origin": "*",
            "Access-Control-Allow-Headers": "*",
            "Access-Control-Allow-Methods": "*"
        },
        body: crypto
    		.createHmac('sha1', process.env.AWS_SECRET)
    		.update(event.queryStringParameters.to_sign)
    		.digest('base64')
	});
};
```

Am I doing something wrong?

Thanks,

YM_Industries

**Comment by bikeath1337** [comment]
The only request that uses the MD5 digest is the PUT to upload a part. The MD5 digest is not part of the Initiate or Complete upload requests. If your signature isn't matching, then there is some other error in your signing configuration.

To troubleshoot, turn on logging in Evaporate and read the AWS XML error response you get. The AWS response shows the parts of the stringToSign it would use to create the signature. Compare that to what Evaporate uses and you should be able to figure out what is different.

**Comment by YMIndustries** [comment]
Logging is currently enabled. The value of stringToSign is identical to what Amazon is expecting, so I think the problem must be in my signing algorithm. I'm not sure how though, because I tried signing the value myself and got the exact same base64 string.
