### ISSUE TITLE
con.cryptoHexEncodedHash256 is not a function(…)

### ISSUE THREAD

**Issue by lewishealey** [TTLabs/EvaporateJS#283]
Hello, I wonder if you could shine light for me. When I try to upload I get this issue. I followed this tutorial to make Evaporate with Laravel:
http://rjv.im/post/91133470306/using-evaporatejs-with-laravel-php

```
var _e_ = new Evaporate({
  signerUrl: '/sign_auth',
  aws_key: 'Not showing',
  bucket: 'wedit-media',
  aws_url: 'https://s3-eu-west-1.amazonaws.com',
  awsSignatureVersion: '4',
  awsRegion: 'eu-west-1',
  s3Acceleration: true
});
```

**Comment by bikeath1337** [comment]
@lewishealey you neglected to report:

- what version of Evaporate? You should be using the latest version 2.0.

The blog posting you linked to is more than 2 years old. Evaporate is an active project and has improve a lot. The existing project readme has been useful for the community, though it certainly isn't perfect. :)

One obvious missing element is that you've not defined your crypto `con.cryptoHexEncodedHash256`. The readme gives a couple of examples that you can use, depending on your configuration.

**Comment by bikeath1337** [comment]
Should I keep this open, @lewishealey ?

**Comment by leolorenzoluis** [comment]
Hello,

I get the same message when viewing the console. I tried to read the readme, but obviously that missing element is not so obvious for me. How do I define my own crypto `con.cryptoHexEncodeHash256`?

**Comment by bikeath1337** [comment]
@leolorenzoluis the docs give two examples for this, one for node.js and one for the AWS SDK. Please search for `cryptoHexEncodedHash256`.
