### ISSUE TITLE
Issue with large file upload (>= 5GB)

### ISSUE THREAD

**Issue by PrabhanjanKumar** [TTLabs/EvaporateJS#284]
Dear Team, We have a requirement to perform large file uploads upto 80 GB to S3 using JavaScript client. Hence we are trying EvaporateJS as it has lot of other nice features such as pause, resume cancel, progress, error handling etc.. We are able to upload 1GB file successfully. But, when we upload large files ie., >= 5GB, it runs out of memory. We took a heap snapshot to analyze the memory usage. We see that the number of Uint8Array and filereader objects are increasing in number as the parts are getting uploaded and after 1GB it stops. Looking at the below function in evaporate.js, we see that each time a part is read, new Uint8Array() and new FileReader() objects are getting created which are not releasing memory after the file part is uploaded. Could you please let us know if we are missing something?

function PutPart.prototype.payloadFromBlob();

Thanks in advance,
Prabhanjan

**Comment by PrabhanjanKumar** [comment]
Few more inputs, we have tried with part size, default 6 MB, 10 MB, 100 MB etc.. using Chrome browser, the ram available on the system is 2GB and hard disk space of 10GB, concurrent upload set to default ie., 5. 

Thanks,
Prabhanjan

**Comment by bikeath1337** [comment]
@PrabhanjanKumar Please reply with your evaporate configuration and which version you are using.

**Comment by PrabhanjanKumar** [comment]
@bikeath1337

We were using version 2.0.3, master branch, we are now using stable branch and able to upload 5GB files without any issue. Thanks so much for your timely response.

Prabhanjan Kumar

**Comment by bikeath1337** [comment]
Good news. If I were to patch 2.0.3 would you be able to verify the change? We really want to start promoting a stable v2 with promise support. Thanks!

--
Bobby
646-321-6011

**Comment by PrabhanjanKumar** [comment]
Yes, we can verify and update here. EvaporateJS is awesome..

**Comment by bikeath1337** [comment]
I pushed a commit to branch https://github.com/TTLabs/EvaporateJS/tree/memory_fix_try. I think it might reduce memory consumption. Would you be able to confirm on your large file? Thank you.

**Comment by PrabhanjanKumar** [comment]
Thanks for adding the fix, We are testing this and will have the test results ready latest by tomorrow(12/23/2016) EOD IST.

Prabhanjan

**Comment by bikeath1337** [comment]
I identified the issue with retained memory in 2.0.3, addressed it and released as 2.0.4.

**Comment by bikeath1337** [comment]
Should I close this issue?
