### ISSUE TITLE
Ask about the license

### ISSUE THREAD

**Issue by lcd78706** [TTLabs/EvaporateJS#286]
Hi~ I am a member of cdnjs project.
I want to add this library, but the license mentioned in https://github.com/TTLabs/EvaporateJS/blob/master/package.json#L36 and in https://github.com/TTLabs/EvaporateJS/blob/master/README.md#license are different.
I want to check which license I should write.

https://github.com/cdnjs/cdnjs/issues/10061

**Comment by bikeath1337** [comment]
Hi, there, @lcd78706 . Thanks for the reply. The license was correct in the readme, so I just updated the package.json file now. I do hope that's still compatible naming with webjars. :)

**Comment by lcd78706** [comment]
Thanks!
