### ISSUE TITLE
Usage with modern browser env (Webpack/Babel)

### ISSUE THREAD

**Issue by slorber** [TTLabs/EvaporateJS#288]
Hi,

I am using Webpack + Babel.
I use S3 signature V4 and need md5/sha256.

I'm starting to use your lib but it took me quite a while to setup, mostly the cryptographic part.

I first tried to use the "crypto" package, but unfortunatly I'm not really sure to understand how to load that node native package inside a browser environment.

Then I tried to use the AWS package. This was very easy to setup, but once running, I noticed that loading the whole AWS SDK just for 2 crypto functions was really too much (adds at least 1mb to final Webpack bundle size)

The I tried back to use the "crypto" based code. I tried to install this lib: https://github.com/crypto-browserify/createHash but it actually did not work because of a problem related to ArrayBuffer not having the `_isBuffer = true` attribute, inside `isBuffer()` method. I suspect it may be a conflict due to using Babel polyfill.

After trying different libraries I finally got a working setup, for those interested:

```javascript
import SparkMD5 from "spark-md5";
import SHA from "jssha";

const config = {
      ...
      cryptoMd5Method: (data) => btoa(SparkMD5.ArrayBuffer.hash(data, true)),
      cryptoHexEncodedHash256: (data) => {
        const sha = new SHA("SHA-256", "TEXT");
        sha.update(data);
        return sha.getHash("HEX");
      },
};
```

So I think the lib should do a better job at documenting recommended crypto to use so that users don't loose too much setup time, because examples are all using AWS SDK which is very heavy for real production usage, and I can't understand how to load that "crypto".

A simple approach would be to expose a package with recommended implementations: 

```javascript
  import Evaporate from 'evaporate';
  import {cryptoMd5Method,cryptoHexEncodedHash256} from 'evaporate/crypto';

    const config = {
      ...
      cryptoMd5Method: cryptoMd5Method,
      cryptoHexEncodedHash256: cryptoHexEncodedHash256,
    };
  
    Evaporate
      .create(config)
      .then(...)
```

**Comment by bikeath1337** [comment]
Thank you very much. It looks like you did not fully ready the Readme beyond the sample code. The options documentation gives 3 examples: AWS SDK, Spark (for signature version 2.0) and Crypto.

As much as I would like to assist anyone with cryptographic help, that needs to be considered as out of scope for Evaporate documentation. If you need a node module, many of the core libs are available as JS includes that you can reference through a CDN or download and use from your own servers.

EvaporateJS supports both AWS signature versions: 2 and 4. The cryptographic requirements for these signatures are specified by AWS and fully covered in their documentation. There are many libraries out there for you to choose. As a courtesy, I included 3 ready-to-use examples in the Readme for the `cryptoMd5Method'. These examples work for signature version 2 and 4.

The readme for `cryptoHexEncodedHash256` does _not_ include an example for plain old browsers, but it looks like you can provide that. Please go ahead and create the pull request that clarifies the examples for `cryptoHexEncodedHash256`.

Thanks!

**Comment by slorber** [comment]
thanks I'll try to enhance the doc soon.

Also worth mentionning this project for those wanting to set Content-Disposition header on uploaded files: https://github.com/jshttp/content-disposition

**Comment by bikeath1337** [comment]
Thanks, @slorber
