### ISSUE TITLE
When using AWS Signature v4, customAuthMethod has no way of knowing the Canonical Request

### ISSUE THREAD

**Issue by YMIndustries** [TTLabs/EvaporateJS#293]
Hi,

I'm implementing a file upload mechanism using EvaporateJS, and I have a use case where I need to restrict what directories (prefixes) each user is allowed to upload into. My plan is to have my signing API inspect the Canonical Request in order to check where the user is attempting to upload to.

Unfortunately, using a customAuthMethod there appears to be no way to retrieve the Canonical Request, or even just the components that make it up. customAuthMethod is only passed the stringToSign. As I understand it, the stringToSign is irreversibly hashed, so there's no way for me to extract the details I need from it.

Is there a way to provide this information to my API that I'm missing?

Thanks,

Josh

**Comment by bikeath1337** [comment]
There is a discussion on this (it's rather long) but essentially, it's agreed that Evaporate should make the canonical request available for a signer. I saw your PR but cannot merge a change that exposes the entire internal implementation object to the signer.

My proposal would be to provide the canonical request as an optional parameter for all signing methods.

**Comment by YMIndustries** [comment]
I understand your reasoning there. I was initially planning on just returning the canonical request, but then I realised that the AWSSignatureV2 code doesn't expose a .canonicalRequest() function, where AWSSignatureV4 does. Maybe we can alter AWSSignatureV2 to have the same footprint as V4? Also, it's kinda goofy to generate the canonical request twice, so it should probably be generated externally and then passed in to stringToSign() instead of the current way where it's generated inside stringToSign().

I'm happy to amend my PR if you think these changes would be good, the main reason for my initial PR was as a talking point.

**Comment by mhenkel1** [comment]
This is basically the same as #219 for now you can do what I suggested in #219 and hijack the `cryptoHexEncodedHash256` function for V4, and in V2 you could hijack the `cryptoMd5Method` function.

**Comment by bikeath1337** [comment]
Should be addressed after we merge #300.

**Comment by bikeath1337** [comment]
Addressed in #300
