### ISSUE TITLE
Unable to upload at certain times

### ISSUE THREAD

**Issue by saroj4321** [TTLabs/EvaporateJS#295]
I have successfully setup the project and able to upload files to my S3 bucket as well. 
I am facing some weird issue. I get "The request signature we calculated does not match the signature you provided." during the day. And it works fine after sometime. 
I am unable to figure out the exact reason. Can you please help.

Here is the snippet of code that I use to generate the key.
```
    public static final String HMAC_SHA1_ALGORITHM = "HmacSHA1";
    public static final String ALGORITHM = "HmacSHA256";
    public static final String UTF8 = "UTF8";
    public static final String AWS4 = "AWS4";
    public static final String REGION = "us-west-2";
    public static final String SERVICE = "s3";
    public static final String AWS4_REQUEST = "aws4_request";
	
	//Controller
	public void generateFileUploadSignature(@RequestParam("to_sign") String toSign,
            HttpServletResponse response) throws Exception {
        response.getWriter()
                .write(Hex.encodeHex(HmacSHA256(toSign, getSignatureKey())));
    }
	
    public byte[] HmacSHA256(@NotNull String data, @NotEmpty byte[] key)
            throws NoSuchAlgorithmException, InvalidKeyException, IllegalStateException, UnsupportedEncodingException {
        Mac mac = Mac.getInstance(ALGORITHM);
        mac.init(new SecretKeySpec(key, ALGORITHM));
        return mac.doFinal(data.getBytes(UTF8));
    }

    public byte[] getSignatureKey()
            throws UnsupportedEncodingException, InvalidKeyException, NoSuchAlgorithmException, IllegalStateException {
        byte[] kSecret = (AWS4 + amazonS3Service.getSecretAccessKey()).getBytes(UTF8);
        byte[] kDate = HmacSHA256(new SimpleDateFormat("YYYYMMdd").format(new Date()), kSecret);
        byte[] kRegion = HmacSHA256(REGION, kDate);
        byte[] kService = HmacSHA256(SERVICE, kRegion);
        byte[] kSigning = HmacSHA256(AWS4_REQUEST, kService);
        return kSigning;
    }
```

**Comment by bikeath1337** [comment]
If AWS is reporting that your signature is invalid, that is almost always due to an error in how you sign your requests. If it happens at a particular time, then my guess is that you're not considering or using the correct timestamp that Evaporate provides you and uses in the string to sign.

Get the XML error response from AWS and format it so it's readable, then turn on debug in Evaporate and compare the string_to_sign components used with those reported from AWS. They will differ if the signatures differ and you can use that information to troubleshoot your signer.

**Comment by saroj4321** [comment]
Thank you for your reply.

I noticed that when my server timezone date matches the GMT timezone date, it uploads without issues. Please let me know if you have any inputs on this?

**Comment by bikeath1337** [comment]
I don't have any more input on this. If AWS replies with an invalid signature, then the only explanation I know of at this time is that you're not signing the request correctly.
