### ISSUE TITLE
initiate error, AWS Code: SignatureDoesNotMatch

### ISSUE THREAD

**Issue by ile** [TTLabs/EvaporateJS#296]
Hi,

I'm trying to configure EvaporateJS (2.0.6), but I'm running into this issue which I haven't been able to solve. Any help would be very much appreciated.

```
initiate error: mybucket.xxx.yyy/s/2e31d022-705f-47f3-9d5d-0841f20a4413/joulurauha.png AWS Code: SignatureDoesNotMatch, Message:The request signature we calculated does not match the signature you provided. Check your key and signing method.status:403
```

I used to upload to S3 with pre-signed urls, with almost the same setup (same bucket, key, secret, cors config etc.), so I suspected everything is set there correctly.

I tried with a new key/secret as well, as I read from [here](http://stackoverflow.com/questions/2777078/amazon-mws-request-signature-calculated-does-not-match-the-signature-provided) that non-alphanumeric characters may cause problems in the secret. This new secret has only alphanumeric characters, but it didn't help.

Here's how a configure Evaporate initially:

```js
    Sha256 = require 'sha.js/sha256'
    sha256 = new Sha256()

    config =
      aws_key: 'my-aws-key',
      bucket: 'mybucket.xxx.yyy',
      awsRegion: 'us-east-1',
      computeContentMd5: true,
      cryptoMd5Method: (data) -> btoa(SparkMD5.ArrayBuffer.hash(data, true))
      customAuthMethod: @signEvaporateRequest
      cryptoHexEncodedHash256: (x) -> sha256.update(x, 'utf8').digest('hex')

```

Any help appreciated.... Thanks.

**Comment by bikeath1337** [comment]
Please summarize the error you are seeing. I shouldn't have to review log files in order to know the high level issue you're having.

thank you

**Comment by ile** [comment]
It should be there now, I accidentally left it out at first.

**Comment by ile** [comment]
This is how I do the signing (I do it on the server, not AWS lambda, but on the server. I guess this shouldn't matter where it's done). :

```
crypto = require 'crypto'
signature = crypto.createHmac('sha1', secretAccessKey).update(stringToSign).digest('base64')
```

and this is where `stringToSign` comes from:

```
customAuthMethod: @signEvaporateRequest
```
```
signEvaporateRequest: (signParams, signHeaders, stringToSign, signatureDateTime) =>
```

**Comment by ile** [comment]
I realized I'm signing wrong. That was the way I understood from the docs, but that's the version 2 way I guess.

Now I changed it to V4, but it still doesn't work....

**Comment by ile** [comment]
Ok, problem solved. I used sha.js wrong, I needed to do `new Sha256()` every time, not just once.

So, this can be closed. But, I would like to suggest that you state it more clearly what type of signing method (with examples) you need to use. The links point to V2 example only (I think). I would suggest you point to both versions (V2, V4), so it will then be more clear.

**Comment by bikeath1337** [comment]
Thank you for the extra feedback and comments about the documentation. V2 is pretty much only used in the US and the entire community, including AWS recommends V4. It's never been a requirement for Evaporate to explain how to create a signing algorithm because AWS creates that standard and supports it.

We provide signing examples as a courtesy to help users get started and our goal is to attempt to make it as easy as possible to upload using S3 multipart uploads. I'd review a PR with improvements to the README gladly.

In the meantime, I made this change: https://github.com/TTLabs/EvaporateJS/commit/4056d679b21e6277c5882f9b3d30509ad4bb28ac
