### ISSUE TITLE
Retry doesn't give up if file is missing in S3

### ISSUE THREAD

**Issue by ile** [TTLabs/EvaporateJS#299]
I bumped into an issue where the file doesn't exist in S3, but Evaporate tries to re-upload it anyway (after getting the info from localStorage). This retry process doesn't seem to end at all, so it keeps trying even though it doesn't have a chance to succeed (the file is missing in S3).

I would think Evaporate needs to stop trying at some point (after a few tries?) and then upload the whole file again?

**Comment by bikeath1337** [comment]
@ile Please check the AWS response for your request. Most likely it reports "Your proposed upload is smaller than the minimum allowed size". This is because AWS minimum part size if 5MB.

Evaporate does not validate for that (yet), so please use the minimum part size required by AWS.

Also see #240

**Comment by bikeath1337** [comment]
There is test coverage for this. If the file is not found on S3, Evaporate will retry the file, which is correct behavior. I suspect something else is happening. Please reply with the AWS XML error response to the request that's failing.

See #240 for retries.

**Comment by ile** [comment]
I probably had the too small partSize here as well. This can probably be closed.
