### ISSUE TITLE
Use existing etags in new session

### ISSUE THREAD

**Issue by tomsaffell** [TTLabs/EvaporateJS#30]
Let's say a file is 60% done, and the upload irrecoverably fails. Then the user tries to upload again a few hours later (not necessarily from the same browser or even machine). We could 'resume' the upload starting at 61%, if we have the etags for the first 60%. 

1. as etags of completed parts are received, POST to an application server (probably in batches, to guarantee order)

2. when a file is passed to evaporate, check with application server whether some etags already exist for the file (file would need some 'unique' id, which would probably have to be name+lengthInBytes). Maybe could be hash of file, but not if it requires entire file being loaded into memory :)

3. if existing etags are available then use those, rather than uploading the corresponding part

Need to check how long the uncompiled parts are kept by AWS.

**Comment by bikeath1337** [comment]
This issue has been resolved in 1.0.0.
