### ISSUE TITLE
PolyFix for IE 11 : evaporatejs

### ISSUE THREAD

**Issue by Prashant-Chouhan** [TTLabs/EvaporateJS#303]
Hi TTLabs,
Evaporate is failing in IE 11. It is saying Promise is undefined
Can you please let me know , which polyfill will work best 

Thanks 
--
Prashant

**Comment by bikeath1337** [comment]
Hi @Prashant-Chouhan , did you try the polyfill referenced in the readme here https://github.com/TTLabs/EvaporateJS#browser-compatibility ?

**Comment by Prashant-Chouhan** [comment]
Hi TTLabs
I just got to work with 
core-js 2.4.1
 * https://github.com/zloirock/core-js
 * License: http://rock.mit-license.org
 * © 2016 Denis Pushkarev
It is awesome and work as a charm
