### ISSUE TITLE
Basic v4 implementation fails

### ISSUE THREAD

**Issue by Floriferous** [TTLabs/EvaporateJS#304]
Hi, I'm new to AWS S3 and its intricacies.

I've tried a lot of different ways to get a basic sample app up, with no success. I fail to understand what is required, what isn't, and how everything is tied together. (everything is implemented on the client for simplicity)

(also weird: Not sure why, but it seems like I have to duplicate the aws_key, bucket, etc. in the signParams object, or else I can't have access to them in my signing function.)

This is my config object:
```
  var config = {
    customAuthMethod: function (signParams, signHeaders, stringToSign, signatureDateTime) {
      return new Promise(function (resolve, reject) {
          resolve(getSignature(signParams, signHeaders, stringToSign, signatureDateTime));
      });
    },
    aws_key: '***',
    bucket: '***',
    awsRegion: 'eu-central-1',
    logging: true,
    cloudfront: false,
    computeContentMd5: true,
    cryptoMd5Method: data => crypto.createHash('md5').update(data).digest('base64'),
    cryptoHexEncodedHash256: data => crypto.createHash('sha256').update(data).digest('hex'),
    // signHeaders: {
    // },
    signParams: {
      aws_key: '***',
      aws_secret: '***',
      bucket: '***',
      awsRegion: 'eu-central-1',
      service: 's3',
    },
  };
```

my signing function looks like this:
```
const getSignature = (signParams, signHeaders, stringToSign, signatureDateTime) => {
  const timeStamp = signatureDateTime.substr(0, 8);
  const date = hmac('AWS4' + signParams.aws_secret, timeStamp);
  const region = hmac(date, signParams.awsRegion);
  const service = hmac(region, signParams.service);
  const signing = hmac(service, stringToSign);
  const final = hexhmac(signing, stringToSign);
  return final;
};
```

And with this, I get the error "AWS Code: SignatureDoesNotMatch". It seems to me like I must have plugged something improperly, and that it could be much simpler!

**Comment by bikeath1337** [comment]
If you need help getting AWS signatures to work, the appropriate forum is one related to AWS and not Evaporate because Evaporate isn't responsible for signing -- just giving you what you need to sign. An even better forum would be Stackoverflow.

That being said, you didn't follow the AWS directions for V4 signing.

```javascript
const signing = hmac(service, stringToSign);
```

is not correct, it should be

```javascript
const signing = hmac(service, "aws4_request");
```

The examples given in evaporate show equivalent code. 

Also, you should NEVER send your private key unless that key is restricted to an AWS Lambda.
