### ISSUE TITLE
Could aws_key be removed from IMMUTABLE_OPTIONS?

### ISSUE THREAD

**Issue by HugoCrd** [TTLabs/EvaporateJS#309]
Hi,

Thanks for your work on EvaporateJS and the awesome version 2!

I'm wondering why `aws_key` has to be part of `IMMUTABLE_OPTIONS`?
In our use case, `aws_key` (along with `bucket`), is dynamically given by our API when beginning an upload.
Removing `aws_key` from the list does work for me, but I suspect there's something wrong about it.

Hugo

**Comment by bikeath1337** [comment]
It's possible that with the Promise-based implementation, that aws_key could change per request. In earlier implementations, it was essential that it remain immutable. After the refactoring, we didn't look at the immutable options, to see which still applied.

**Comment by HugoCrd** [comment]
Good news!
What can I do to help you on this one?

**Comment by bikeath1337** [comment]
1. verify and create specs for the existing behavior.
2. update your feature branch to support the improvements.
3. verify that all specs cover the behavior; pass and nothing breaks elsewhere
4. submit a pull request for review.

**Comment by bikeath1337** [comment]
OK..I had some free time...what do you think? #312 .

**Comment by HugoCrd** [comment]
Thanks!

Your PR is about `aws_url`, not `aws_key` tho. 
But based on this I'll make a PR for `aws_key` today ;)

Thanks for your time!

**Comment by bikeath1337** [comment]
Merged in #314
