### ISSUE TITLE
Who Wants to Help Creating a Wiki for EvaporateJS?

### ISSUE THREAD

**Issue by bikeath1337** [TTLabs/EvaporateJS#313]
If anyone wants to contribute to creating a Wiki for Evaporate, I'd like to collaborate on it. I think the README is getting a bit unwieldy.

**Comment by jakubzitny** [comment]
Hi @bikeath1337, I was finishing my thesis for past few months so I've been quite busy. I have some free time now though so I thought I could help with some things. Wiki seems like a great starts.

Check out -> https://github.com/TTLabs/EvaporateJS/wiki.

There are still some things that need to be polished:
- [ ] sidebar
- [ ] fixing links
- [ ] reducing Readme.MD

For the Sidebar, I don't think I have rights to do that so if you find time, I suggest following order of sections and subsections with links to the pages:
- API
  - create
  - add
  - pause
  - resume
  - cancel
- Compatibility
- Important Usage Notes
- Examples
  - Configuring S3 Bucket
  - ReadableStreams support
- Migration
- Integrations

**Comment by bikeath1337** [comment]
Thanks @jakubzitny ! I'm in the middle of wrapping up a couple of features and am doing a lot of multi-tasking, so give me a couple of days.

**Comment by bikeath1337** [comment]
Thanks, @jakubzitny I merged the PR so will close this "call to action" ticket.
