### ISSUE TITLE
EvaporateJS now requires localStorage?

### ISSUE THREAD

**Issue by YMIndustries** [TTLabs/EvaporateJS#316]
Hi,

I'm running EvaporateJS in a Web Worker, so this is similar to #308. Web Workers don't have access to local storage. In EvaporateJS 2.0.6 this wasn't an issue, but I've just updated to 2.0.8 and suddenly my uploads don't work. Here's the error I receive:

```
Uncaught (in promise) TypeError: Cannot set property 'firstMd5Digest' of undefined
    at ext (evaporate.js:2029)
    at extend (evaporate.js:2035)
    at FileUpload.updateUploadFile (evaporate.js:754)
    at evaporate.js:1391
```

This is caused by the fact that getSavedUploads will always return {} if localStorage is not supported. I think this will also cause issues for Safari Private Browsing, as localStorage is disabled in that context.

In the historyCache object there's a function to test if it's supported. I think if it's not supported, historyCache should implement a basic fallback to at least allow for temporary storage.

Thanks,

YM_Industries

**Comment by bikeath1337** [comment]
Interesting, it's not supposed to fail, but simply not use any caching and I thought we had specs for it. Looks like we introduced an issue after 2.0.6. If you've done troubleshooting, would you be able to submit a PR?

**Comment by YMIndustries** [comment]
I know what causes this issue now, it was the removal of Object.assign (#307). The extend method that's now used fails if the second argument is undefined, and I think Object.assign didn't. Submitting a PR now.
