### ISSUE TITLE
when we try downloading file which is uploaded using evaporatejs, is not downloading in browser, instead it is opening in window

### ISSUE THREAD

**Issue by AshwiniMetgudmath** [TTLabs/EvaporateJS#321]
Hi,
when we try downloading file which is uploaded using evaporatejs, is not downloading in browser, instead it is opening in window.
I tried setting contentType while creating evaporatejs obejct, but still it is not working.

**Comment by AshwiniMetgudmath** [comment]
Hi,
Is there any option to set Content-Disposition parameter while upload?

**Comment by bikeath1337** [comment]
@AshwiniMetgudmath You can set unsigned headers using the documented option `notSignedHeadersAtInitiate`.

**Comment by AshwiniMetgudmath** [comment]
Thank you.
 It's working fine now.
