### ISSUE TITLE
Object does not support this action in IE

### ISSUE THREAD

**Issue by ryansydnor** [TTLabs/EvaporateJS#325]
Looks like the [URL](https://developer.mozilla.org/en-US/docs/Web/API/URL) module is [not supported](https://developer.mozilla.org/en-US/docs/Web/API/URL#Browser_compatibility) by IE. This [commit](https://github.com/TTLabs/EvaporateJS/commit/7bbaa625ca2a9134d9423bf6d20916325b55ee77) seems to be the culprit, because if I revert back to using `document.createElement` I get the expected behavior.

Is there any other information I can provide you to help?

**Comment by bikeath1337** [comment]
Merged #326 . Thank you.
