### ISSUE TITLE
$cancelAll() and $pauseAll() is not working when multiple files are uploading

### ISSUE THREAD

**Issue by AshwiniMetgudmath** [TTLabs/EvaporateJS#327]
Hi,

I am using $add() for muliple files upload at a time, and $pauseAll() and $cancelAll() for pause and cancel, but $pauseAll and $cancellAll are working fine when single file is uploading but these pause and cancel are not working when multiple files are uploading.

can you please help me with this??

**Comment by bikeath1337** [comment]
This is a question for https://github.com/uqee/angular-evaporate.
