### ISSUE TITLE
xAmzHeadersCommon not working

### ISSUE THREAD

**Issue by pratik2pris** [TTLabs/EvaporateJS#328]
Hello

I am using temporary credentials for upload and add the following as per the documentation.

xAmzHeadersCommon : {'x-amz-security-token':'the-long-session-token'} . But it seems it is not adding as header when POST , GET , DELETE , HEAD request execute. I can not see the header via console.

Could you help me ?

Also we are setting expiration of temp credential for 1 hour but there is chance that 1 hour is not sufficient for upload as we are uploading very large files ( 50 GB each ). And as per the AWS documentation we can only set up to 12 hours expiration time. 

So in this case how we can change this xAmzHeadersCommon during uploading.

Looking forward for your help.

Regards,
Pratik

**Comment by bikeath1337** [comment]
Evaporate has explicit test coverage for this in `test/common-case.spec.js`. Please review these specs to understand what is happening in your implementation.

If you enable debug, you should see the headers in the output for the "stringToSign" debug.

As for changing the the header, there is currently no support for that. If such a feature were to be added, I'm thinking it should probably act like `makeSignParamsObject` where you can pass a method as the header value. This would allow you to return the refreshed token.

**Comment by pratik2pris** [comment]
Thanks for the answer.

Should I request you for makeSignParamsObject function so it can solve our problem. Also will be good if we can get function which will be able to change the aws_key also.

Thanks for your help.

**Comment by bikeath1337** [comment]
Sure, go ahead and create a with test coverage that follows the pattern used by makeSignParamsObject.

**Comment by pratik2pris** [comment]
Thanks!

I am going to create following functions as per my requirement. And I believe that it will be usable for others too.

1) Add / Get Custom data ( User can associate the custom data to file / object and then can get as per their requirement )

2) makeSignParamsObject as we discussed.

3) makeAWSKeyObject ( This will allow user to pass awskey same as signparam )

Once done I will submit for your approval. I hope it make sense

**Comment by jakubzitny** [comment]
Just fyi @pratik2pris, I am using `xAmzHeadersCommon` for `x-amz-security-token` and it works correctly.

**Comment by pratik2pris** [comment]
Thanks @jakubzitny 

I am able to use this now. But can you let me know how you refresh this when expire ?

**Comment by jakubzitny** [comment]
As @bikeath1337 already mentioned, changing headers during upload is not available in Evaporate. I am not even sure it is available in AWS, is it?

Odo you mean something else by the "refresh"?

**Comment by bikeath1337** [comment]
Hello,

1. this should be a separate pr with full test coverage. i’m really not keen on adding features to Evaporate “per their requirement”. That isn’t was open source software is for, so I will probably look at these changes with skepticism.
2. ok. Again, with full test coverage
3. there is no need for this as we already support changing the aws_key per .add()

**Comment by pratik2pris** [comment]
Hello

Yes I agree to not add anything as per special request. But can not we do following ?

xAmzHeadersAtInitiate
xAmzHeadersCommon 

above can be promise function as well as the existing so in this case user can pass the promise function here as per their requirement which will check token expire and generate againg.

e.g..

xAmzHeadersAtInitiate : function () {
                    // Check if token is expire or not
                    return new Promise(function (resolve, reject) {
                        resolve({
                            'x-amz-acl': 'private',
                            'x-amz-security-token': // Token
                        });
                    })
                }

3) Yes I know that we can add aws_key when add. But let's assume that temp token is expire and when generate new one it change the aws_key also. So in that case the signature will be invalid. So need function where we can change the aws_key too.

If above can be implemented then I believe it will useful for all.

let me know your thoughts.

**Comment by pratik2pris** [comment]
there is no need for this as we already support changing the aws_key per .add()

I check deeply and found that it can not be override. 

return ['AWS ', con.aws_key, ':', this.request.auth].join('');
authParts.push(['AWS4-HMAC-SHA256 Credential=', con.aws_key, '/', credentials].join(''));

in both above place it use the master configuration. Could you advise ?

**Comment by pratik2pris** [comment]
Also I can see that 2.0.9 has ability to change aws_key for per file but when I try to install 2.0.9 it gives me following error.

No tag found that was able to satisfy 2.0.9

**Comment by bikeath1337** [comment]
I neglected to push the tag to the remote yesterday, but it is there now. 

Please check the test coverage for this and see if there is an issue. Thank you.

**Comment by pratik2pris** [comment]
Thanks for the message.

I am able to install the 2.0.9 and now it returns the following error.

TypeError: historyCache is undefined at line 2045

var uploads = JSON.parse(historyCache.getItem('awsUploads') || '{}');

For aws_key override I am using as follow as per test coverage

file.objEvaporate.add(addConfig, {
aws_key : ..... 
}

But I can not see any code related to that in latest version.
e.g.
return ['AWS ', con.aws_key, ':', this.request.auth].join('');

it is still using main configuration aws_key. Let me know if I am wrong.

Can you help me to solve this issue ?

Thanks for your help so far

**Comment by bikeath1337** [comment]
If historyCache isn't defined, then Evaporate didn't fully instantiate and you ignored the 'reject' response to its promise. My guess is that you then went ahead and tried to use Evaporate, which would try to use the uninitialized `historyCache`.

I also manually confirmed (in agreement with the specs!) that I can change the aws_key on Add. I updated `example/evaporate_example.html` to allow the key to be changed in the form. You should be able to confirm this using the "unsafe JavaScript custom auth method".

**Comment by pratik2pris** [comment]
Thanks for the information. Yes I can change the aws_key
