### ISSUE TITLE
Files are not available on s3

### ISSUE THREAD

**Issue by IMfenil** [TTLabs/EvaporateJS#345]
![upload](https://cloud.githubusercontent.com/assets/19950756/24826929/f9518dbe-1c5e-11e7-8371-0503aae5ce38.png)
Hello,

We are trying the demo and we are uploading few files. We can see the chunks uploading to the S3 but file is not available on the S3.

 xml version="1.0" encoding="UTF-8"?
CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/"
    CORSRule
         AllowedOrigin>*</AllowedOrigin 
        AllowedMethod>GET</AllowedMethod 
        AllowedMethod>POST</AllowedMethod 
      AllowedMethod>PUT</AllowedMethod 
    AllowedHeader*AllowedHeader 
    CORSRule
CORSConfiguration

Can you help us what we are missing from our side?

Thanks,
Fenil

**Comment by bikeath1337** [comment]
1. What version of Evaporate are you using?
2. How are you initializing evaporate? (you do not need to include secrets)
3. How are you adding a file to the evaporate instance?

The COMPLETE request will be sent when all of the parts have successfully uploaded. Its payload is an XML document describing to S3 all the parts that need to be combined to create the file. Unless that request successfully completes, your file will never be visible on S3.

If all of the part PUTs completed successfully, you should see the COMPLETE request. If you do not see that request, then the parts have not completed and / or consequently not failed either. In any case you should see the status of these on the XHR network tab of Chrome. you can use the same panel to inspect the XML document sent to complete the file upload.

If you can reply filling in the requested information, I may be able to help.

**Comment by bikeath1337** [comment]
Since you have not replied in 17 days, I am going to assume that you have resolved the issue on S3.
