### ISSUE TITLE
Memory issue on Chrome 

### ISSUE THREAD

**Issue by ebuitweb** [TTLabs/EvaporateJS#355]
Hi,

We try to use your library to upload large video file on s3 (multipart + s3 accelerated) but on chrome we have some memory leak with all your versions except version 2.00 or below. 

We have the same issue on windows (windows7) or mac. And the issue is more visible when you have a very good internet/connection (we test with 125mbits/s or more) 

Our bucket is in ireland and we use SIGNATURE VERSION V4.
It's working well on firefox.

![evaporate_network_usage](https://cloud.githubusercontent.com/assets/15612181/25525751/a2ab43c6-2c10-11e7-93d5-918c2bca786e.png)
[evaporate_2.1.0_config.txt](https://github.com/TTLabs/EvaporateJS/files/964120/evaporate_2.1.0_config.txt)
![evaporate_chrome_version](https://cloud.githubusercontent.com/assets/15612181/25525750/a2a6b392-2c10-11e7-95bc-e3467cbc398e.png)
![evaporate_memory_usage_1](https://cloud.githubusercontent.com/assets/15612181/25525749/a2a5d65c-2c10-11e7-8796-66b39b2c6c49.png)
We test with file bigger than 3Go.

Thanks for your help

**Comment by bikeath1337** [comment]
Please do the same tests using `example/evaporate_example.html`, if possible. You can use the javascript signing methods if you plug your keys into the UI. Any reported memory leaks were explicitly resolved in 2.0.4 and (which doesn't apply to you) in 2.1.0.

Also, sending screenshots without context does not help unless you are trying to prove that there is an issue. If you've been testing this, please report how frequently the "crashes" occur (as well as what you mean by "crash"). You should also investigate the profile dumps to look for where the  memory is being retained. All of this was done as part of the testing for 2.0.4 and 2.1.0 and the memory footprints were consistently stable as reported by Chrome.

The testing done was primarily on OSX, however there are many other clients with large bases that include Windows. AFAIK, the outstanding Windows issues were resolved in 2.0.9.

**Comment by ebuitweb** [comment]
Hi,
thanks for your reply. 

We just put in our pre-production environnement your EvaporateJs Example and we just fill our AWS KEY, S3 Bucket and aws Region in the form.

In all my test i use the same file (15Go  video file) and the same bucket configuration.

It's always reproductible with chrome (v 55.0.2883.87 and v 57.0.2987.133) on multiple "windows" desktop (windows 7 + windows10).

I add some new screenshots during the upload process to show you how the memory increase on chrome.

About the profil dumps, can you explain me what do you need exactly please.

**Additional tests :** 
I also test with firefox (v51.0 32bits)
![chrome_1](https://cloud.githubusercontent.com/assets/15612181/25713419/eb3677f8-30f4-11e7-977d-304c68497859.png)
![chrome_2](https://cloud.githubusercontent.com/assets/15612181/25713422/eb37eb7e-30f4-11e7-8578-c93dd7dac5d4.png)
![chrome_3](https://cloud.githubusercontent.com/assets/15612181/25713421/eb37ca54-30f4-11e7-8b6c-9540a5712d7f.png)
![chrome_4](https://cloud.githubusercontent.com/assets/15612181/25713424/eb3709ca-30f4-11e7-9dbf-2a390fddea7b.png)
![chrome_6](https://cloud.githubusercontent.com/assets/15612181/25713420/eb3709d4-30f4-11e7-9654-4b1d54375459.png)
![firefox_1](https://cloud.githubusercontent.com/assets/15612181/25713423/eb383962-30f4-11e7-8c01-a97185de3ae5.png)
![firefox_2](https://cloud.githubusercontent.com/assets/15612181/25713427/eb4fe1e8-30f4-11e7-81bd-749f2bedadf7.png)
![firefox_3](https://cloud.githubusercontent.com/assets/15612181/25713425/eb4bc2b6-30f4-11e7-9254-73deb4e397b7.png)
![chrome_5](https://cloud.githubusercontent.com/assets/15612181/25713426/eb4ebae8-30f4-11e7-97cc-bb50f01009e3.png)








 on the same windows desktop and everything is working well. (see screenshots)
With chrome on mac, we also see the memory increase but we don't have a memory limit message.

**Comment by bikeath1337** [comment]
Thanks for the report. Refer to this PR if you are interested. As its description notes, the retention issue was resolved earlier but seems to have recurred, which I suspect is related to a change in the browser's internals.

If you would like to try this branch in advance of merging it, please let me know.

https://github.com/TTLabs/EvaporateJS/pull/359
