### ISSUE TITLE
Question: Can I use this server-side?

### ISSUE THREAD

**Issue by re-jim** [TTLabs/EvaporateJS#361]
This seems to only be usable through a browser.

Can I not just use this server-side with node.js, without interacting with a browser?

**Comment by bikeath1337** [comment]
The description for this node.js package is "Javascript library for browser to S3 multipart resumable uploads for browsers **and with Node FileSystem (fs) Stream Support**".

EvaporateJS does not require a browser environment. The examples folder has and example for electron. This example does use the browser window for ease of showing the example, so it uses the FileUpload object there.

If you want evaporate to upload from a Node FileSystem file, you need to use the `readableStreams` and `readableStreamPartMethod`.

**Comment by re-jim** [comment]
I've tried to use it with `readableStreams` and `readableStreamPartMethod`, however when I run the app using node 6.9.2, I get a message saying something along the lines of "File and Promise must be available".

I haven't tried with electron, however. Is electron also a requirement?

Here is what I was trying:

```
var AWS = require('aws-sdk');
var Evaporate = require('evaporate');
var awsConfig = require('./aws.config.json');
var config = require('./config.json');
var Promise = require('promise');

AWS.config.loadFromPath('./aws.config.json' );
var s3 = new AWS.S3();

var startTime;
var endTime;

if(config.mode === 'standard'){
	//use s3.upload()
	
}else if (config.mode === 'parallel'){
	//use evaporate
	
	
	var params = {
		Bucket: config.bucket,
		Key: 'speedtest'
	}
	var url = s3.getSignedUrl('putObject', params);
	var retrieveUrl = s3.getSignedUrl('getObject', params);
	
	var params2 = {
		signerUrl:url,
		bucket:awsConfig.bucket,
		aws_key:awsConfig.access_key_id,
		readableStreams: true,
        readableStreamPartMethod: function (file, start, end) {
          return fs.createReadStream(file, {start: start, end: end});
        },
	}
	
	Evaporate.create(params2)
	.then(function(evaporate){
		var addConfig = {
			name: 'speedtest',
			file: config.file,
			complete: completeEvent,
			progress: progressEvent
		}
		
		console.log('starting!');
		var startTime = new Date.getTime();
		evaporate.add(addConfig)
		.then(function(){
			console.log('file uploaded');
			console.log('took ' + endTime - startTime + 'ms');
			console.log(retrieveUrl);
		}
		,function(err){
			console.log('error',err);
		});
	})
	.catch(function(err){
		console.log('evaporate err is',err);
	});
	
	function completeEvent(event){
		console.log('complete!');
		endTime = new Date.getTime();
	}

	function progressEvent(event){
		console.log('progress',event);
	}
}
```

**Comment by bikeath1337** [comment]
The docs also write the you need to provide a Promise implementation and a File implementation if your environment doesn't provide it out of the box.
