### ISSUE TITLE
AuthorizationHeaderMalformed - region is wrong

### ISSUE THREAD

**Issue by mgurnani** [TTLabs/EvaporateJS#364]
Hello,

Thanks for a nice library !

I am trying to use it in my project. I have everything in EU Frankfurt region - S3 bucket, Lambda signer function (same as in examples).
When I select files for upload, I see the following error : 

`AuthorizationHeaderMalformed, Message:The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'eu-central-1'`

Do I need to make any changes in signHeaders or signParams to pass the EU region ?

Any help is appreciated !

**Comment by bikeath1337** [comment]
Glad you like it. Please review the docs before creating issues. An option of the #create method is awsRegion. Use that when instantistiin EvaporateJS.
