### ISSUE TITLE
AWS Code: InvalidPart

### ISSUE THREAD

**Issue by rootedbox** [TTLabs/EvaporateJS#365]
Attached is my code using the EvaporateJS s3 uploading library, and the controller code I am using to sign the request. Right now the entire file gets uploaded but then I get "AWS Code: InvalidPart, Message:One or more of the specified parts could not be found.  The part may not have been uploaded, or the specified entity tag may not match the part's entity tag.status:400”

If I refresh the page and upload the file instantly finishes and shows up on s3. This is happening on videos ranging in size from 1 meg to 13 megs.

[issue.zip](https://github.com/TTLabs/EvaporateJS/files/1073572/issue.zip)

**Comment by sagikazarmark** [comment]
Are you trying to upload from the browser? If so, I guess you needed to add CORS headers.

I added the following to nginx:

```
            add_header Access-Control-Allow-Origin '*';
            add_header Access-Control-Allow-Methods 'GET, POST, PUT, OPTIONS';
            add_header Access-Control-Allow-Headers 'authorization,x-amz-content-sha256';
            add_header Access-Control-Expose-Headers 'ETag';
```

**Comment by tomsaffell** [comment]
@rootedbox @sagikazarmark checking the CORS file is a good place to start - that could be preventing the etags from being returned. 

If that doesnt fix it, please post a link to a live page where we can test it.

**Comment by rootedbox** [comment]
that didn't seem to resolve the problem. we've found a work around.. if the progress starts returning 1 a bunch(i.e. it's done) but won't complete. cancel the connection and start a new instance of evaporate and restart the upload.. the upload will instantly complete.

**Comment by sagikazarmark** [comment]
That sounds weird. Anyway, I would double check the CORS thing: we had a number of issues related to them:

- When using minio with an nginx proxy in front of it we had to use HeadersMore module because minio already returns some CORS headers
- CORS headers must be returned for both OPTIONS and POST, PUT requests (therefore it needs to support preflight OPTIONS requests)

In most of the cases the browser console log should tell you if something is wrong with CORS.

**Comment by rootedbox** [comment]
Our CORS setup is with the right options.. Our work around seems to work; so I'm going to just close out the issue. Thanks for some insights!
