### ISSUE TITLE
Signature verification fails when name contains asterisk.

### ISSUE THREAD

**Issue by kog13** [TTLabs/EvaporateJS#375]
Signature verification fails when name contains asterisk.

Appears to be a URL encoding issue similar to the previous fix for exclamation point. PR is currently open under: kog13:asterisk_encoding

**Comment by bikeath1337** [comment]
Should be solved with #374.

**Comment by kog13** [comment]
Any chance there could be a version bump / npm release?

**Comment by bikeath1337** [comment]
Done.
