### ISSUE TITLE
Evaporate.prototype.supported = false on Firefox 55 & Chrome 60

### ISSUE THREAD

**Issue by paolavness** [TTLabs/EvaporateJS#379]
Surely this is wrong, or I am using it incorrectly?

`console.log( 'Evaporate Supported? ', Evaporate.prototype.supported)`

Prints out `Evaporate Supported?  false`

**Comment by bikeath1337** [comment]
Not correct. You always need to work with an instance of Evaporate.

https://github.com/TTLabs/EvaporateJS/wiki/Evaporate.create()

```javascript
Evaporate.create(config)
    .then(
        function (evaporate) {
                console.log( 'Evaporate Supported? ', evaporate.supported)
        },
        function (reason) {
            console.log('Evaporate failed to initialize:', reason);
        });
```

**Comment by paolavness** [comment]
Great, thank you. Was hoping for a check that would not require creating an instance :)

**Comment by bikeath1337** [comment]
I really don't know where to "go" with that response but glad you added a smily face.
