### ISSUE TITLE
Creating File object from Node layer to be uploaded to S3 from a non-browser script.

### ISSUE THREAD

**Issue by anoopdixith** [TTLabs/EvaporateJS#384]
I'm trying to use Evaporatejs to upload files to AWS, but we need to use it not from the browser but from the node layer. Imagine just a javasript script that is trying to upload the "file" object that is supposed to be created from a file path.

But I don't see how this could be done since Evaooratejs uses FileAPI file object that is completely browser based. Is there a way I could use evaporatejs to upload a file from file path and not from the browser?

**Comment by jakubzitny** [comment]
Yes, there is. You need to provide an object with file path into `#add()` and provide some additional config options so Evaporate can handle it. Some info is [here](https://github.com/TTLabs/EvaporateJS/wiki/Support-for-Node.js-FileSystem-(fs)-and-ReadableStreams).

Provided you have the string of file path, the config you want to add to `#add()` is:
```
evaporate.add({
  name: 'myFile',
  file: {
    name: path.basename(filePath),
    path: filePath,
    size: fs.statSync(filePath).size
  },
})
```

**Comment by bikeath1337** [comment]
@anoopdixith , @jakubzitny answered your question. Evaporate does work in browserless node. There is an example [here](https://github.com/TTLabs/EvaporateJS/tree/master/example/electron). 

https://github.com/TTLabs/EvaporateJS/tree/master/example/electron
