### ISSUE TITLE
onError function

### ISSUE THREAD

**Issue by ausinha** [TTLabs/EvaporateJS#4]
Incase something break, the website could notify the user and take other required action.

**Comment by Ryan-Anderson** [comment]
Yes this would be great, as @ausinha suggests, improper CORS config aborts the upload, and there is no way to handle this.

**Comment by bikeath1337** [comment]
Version 1.0.0 fixed a memory leak in the retry process. Evaporate can now retry indefinitely and manage memory efficiently. This version also support canceling an upload, cleaning up properly on both ends.

I'm going to close this issue for now. If someone wants to request the maxAttempts feature, please open a new ticket.

Thanks!
