### ISSUE TITLE
Missing app.yaml for example

### ISSUE THREAD

**Issue by sveinnfannar** [TTLabs/EvaporateJS#41]
In order to run the demo a `app.yaml` file is needed, this file seems to be not checked into git.

**Comment by nickolaykondratyev** [comment]
Any updates on this?

**Comment by tomsaffell** [comment]
sorry. i dont have the file to hand. you basically just need a static handler for the html file, and a script handler for the python file. all the docs are here: https://cloud.google.com/appengine/docs/python/config/appconfig

i'd post it if i had it, but somehow i dont, sorry..
