### ISSUE TITLE
How to upload using Pre-Signed Urls.

### ISSUE THREAD

**Issue by shivalkondwar** [TTLabs/EvaporateJS#420]
How can I upload a file using Pre-Signed Url in EvaporateJS

**Comment by alenzamanyan** [comment]
You can use signerUrl option described here:
https://github.com/TTLabs/EvaporateJS/wiki/Evaporate.create()

The provided URL should hit an endpoint on your server that uses AWS Signature Version 4 for signing the requests. There's documentation here about how to do that on the backend:
https://docs.aws.amazon.com/general/latest/gr/signature-v4-examples.html
