### ISSUE TITLE
ReferenceError: Promise is not defined

### ISSUE THREAD

**Issue by htallur** [TTLabs/EvaporateJS#421]

**Comment by jakubzitny** [comment]
from [wiki](https://github.com/TTLabs/EvaporateJS/wiki/Browser-Compatibility)

>As of v2.0.0, Evaporate requires a browser that supports ES6 Promises. To use Evaporate on those browsers, you must include a compliant Promise polyfill such as es6-promise. Refer to this list of browsers that support Promises.
