### ISSUE TITLE
sendCanonicalRequestToSignerUrl does not send canonicalrequest due to encodeURIComponent not handling \n

### ISSUE THREAD

**Issue by jbfuzier** [TTLabs/EvaporateJS#441]
I noticed that canonical_request sent to the signer is not the canonical request but the canonical_request without the \n in it.

As a result, it is not possible on the server side to compute the hash of the canonical_request to make sure that the data provided by the client in the canonical_request variable is indeed the data that is being signed.

The issue is here : 
https://github.com/TTLabs/EvaporateJS/blob/master/evaporate.js#L1868

One solution is to switch to base64 encoding instead of using encodeURIComponent.
It will however break backward compatibility.
It is also needed to take into account that built in js base64 does not handle utf16, so it the canonical request has non ascii chars, it will fail.

**Comment by jakubzitny** [comment]
PRs welcome :)

Also, why do you think the backwards compatibility will be an issue? We could release this in a new major version with breaking change and document it properly.

Also, you could bypass this by providing `customAuthMethod` instead of `sendCanonicalRequestToSignerUrl`, would that make sense to you?

**Comment by jbfuzier** [comment]
Thanks for the reply.

It is indeed possible to implement this using customAuthMethod, as the function is indeed receiving the canonialrequest as its 5th argument : 

`signParams, signHeaders, stringToSign, signatureDateTime, canonicalRequest`

I think it is a good option if you have a very specific backend such as a lambda. However if you have a standard http backend, you will end up basically repeating the xhr code that already exists around here https://github.com/TTLabs/EvaporateJS/blob/master/evaporate.js#L1882 .

I will try to submit a PR, but I am not very good with js.

**Comment by jbfuzier** [comment]
So sorry, I do not know what I was thinking yesterday, the issue with the \n was on my backend code and not in the js.

If someone needs it, here is a sample of how to check that the string to sign requested by the client matches the canonical request provided by the client. (After that I do some checks on the canonical request based on the user, some user can upload at some specific location. If the user is not allowed, I refuse to sign the request).

```
@app.route('/signer/')
def signer():
    # DO NOT FORGET TO DO SOME AUTHENTICATION
    canonical_request = request.args['canonical_request']
    canonical_request_ba = canonical_request.encode('utf-8')
    canonical_hash = hashlib.sha256(canonical_request_ba).hexdigest()
    expected_hash = request.args['to_sign'][-64:]
    if canonical_hash != expected_hash: #No need for constant time check here, no secrets are used
        logger.error("Cannonical hash is not valid, to_sign and canonical_request mismatch")
        return Response("CANONICAL_MISMATCH", 403)
    # Do some check on the canonical request if needed (path, method used...)
    # Do the signing
```

**Comment by jakubzitny** [comment]
So everything is OK, do you get the `\n` chars properly from Evaporate? If so, we can close this.

**Comment by jbfuzier** [comment]
Yes, the hash matches which proves that the canonicalRequest is exactly the same as on the js side.

Sorry for the trouble.
