### ISSUE TITLE
SignatureDoesNotMatch

### ISSUE THREAD

**Issue by ferrasa** [TTLabs/EvaporateJS#447]
Hello,
  I'm using the examples (SignerV4Example.java and evaporate_example_awsv4_signature.html) for version 2.1.4, but I'm having an issue with authentication: (Status code 403, SignatureDoesNotMatch). I have an upload implementation with blueimp/file-upload and the same authentication process is working ok. Could you help me on this issue? Thanks.

**Comment by aryanchugh816** [comment]
Did you find a solution for this issue ? If yes, can you please share the code here
