### ISSUE TITLE
evaporate_example.html does not set awsRegion on create

### ISSUE THREAD

**Issue by gotu** [TTLabs/EvaporateJS#453]
User can input region in UI-Input, but that value is not set in Evaporate.create
https://github.com/TTLabs/EvaporateJS/blob/master/example/evaporate_example.html#L74

so when bucket is not in region us-west-1 e.g. user changes the input, it results in:
https://github.com/TTLabs/EvaporateJS/issues/364

**Comment by jakubzitny** [comment]
PRs welcome :)
