### ISSUE TITLE
uploading content to a specific folder inside the s3 bucket

### ISSUE THREAD

**Issue by shivgarg5676** [TTLabs/EvaporateJS#459]
I can successfully upload my contents to the s3 bucket but I need to upload the contents to a specific folder inside the bucket which may or might not exist on the bucket. 

Is it possible with evaporate to upload the files to a specific folder inside the s3 bucket?

**Comment by jakubzitny** [comment]
Yes it is, just put a path to the folder inside the s3 bucket to [name](https://github.com/TTLabs/EvaporateJS/wiki/Evaporate.prototype.add()) parameter of `.add()`.

I'll change it in wiki so it's clear.

**Comment by shivgarg5676** [comment]
but this option will only work if the CloudFront option is false otherwise it will not work, because in that case bucket path is present as a subdomain.

**Comment by jakubzitny** [comment]
You can specify `aws_url` in `add()` for that, can you try if that helps? We are using cloudfront=true and upload to subfolders.

**Comment by shivgarg5676** [comment]
sure will try that.
