### ISSUE TITLE
Signature issue for SSE-C

### ISSUE THREAD

**Issue by edenchen123** [TTLabs/EvaporateJS#47]
I am uploading file using Server-Side Encryption with Customer-Provided Encryption Keys (SSE-C), but I got SignatureDoesNotMatch error.

actual request: 

x-amz-acl:private
x-amz-date:Wed, 08 Oct 2014 15:44:52 GMT
x-amz-server-side-encryption-customer-algorithm:AES256
x-amz-server-side-encryption-customer-key:***
x-amz-server-side-encryption-customer-key-MD5:***

AWS calculated:

x-amz-acl:private
x-amz-date:Wed, 08 Oct 2014 15:44:52 GMT
x-amz-server-side-encryption-customer-algorithm:AES256
x-amz-server-side-encryption-customer-key:***
x-amz-server-side-encryption-customer-key-md5:***

the different is MD5 be changed to md5.

I suspect the issue is in 
      function makeStringToSign(request){

            var x_amz_headers = '', to_sign, header_key_array = [];

            for (var key in request.x_amz_headers) {
                if (request.x_amz_headers.hasOwnProperty(key)) {
                    header_key_array.push(key);
                }
            }
            header_key_array.sort();

            header_key_array.forEach(function(header_key,i){
                x_amz_headers += (header_key + ':'+ request.x_amz_headers[header_key] + '\n');
            });

            to_sign = request.method+'\n'+
                '\n'+
                (request.contentType || '')+'\n'+
                '\n'+
                x_amz_headers +
                request.path;
            return encodeURIComponent(to_sign);
        }
    }
any comments?

**Comment by bikeath1337** [comment]
The header lowercase update is in an outstanding pull request to support AWS Signature Version 4.0.

**Comment by bikeath1337** [comment]
Addressed in 1.4.0.
