### ISSUE TITLE
Facing issues while trying to make it work with Backblaze B2's S3 compatible API

### ISSUE THREAD

**Issue by faisalsayed10** [TTLabs/EvaporateJS#482]
Hi, I was trying to make evaporate.js work with backblaze but I'm constantly getting a 400 error saying that it's a CORS issue.

BUT
- [x] All my cors settings are correct (Tried uploading normally with the aws s3 sdk)
- [x] evaporate works fine with s3 buckets but only throwing that error here
- [x] normal uploading with PutObjectCommand / CreateMultipartUpload works

As you can see, it is being quite tricky for me to understand what's wrong. I wanted to take advantage of Evaporate's resumable functionality with backblaze buckets. any help is appreciated 🙌 

This picture is a request made with evaporate and the error I'm getting. As you can see, I'm not getting any access-control headers for some reason
![image](https://user-images.githubusercontent.com/36627266/174429111-91cb2e79-48db-4a40-a62f-ce26c299938a.png)
![image](https://user-images.githubusercontent.com/36627266/174429141-22670fb2-b9fe-437a-b5de-ba975543be15.png)

but other requests made with the aws sdk work perfectly
![image](https://user-images.githubusercontent.com/36627266/174429177-2f38840f-03ac-491c-9aca-a4c9a91731bf.png)

**Comment by GFoley83** [comment]
@faisalsayed10 Did you ever get this to work with Backblaze?

**Comment by faisalsayed10** [comment]
@GFoley83 I don't think I did. Ended up building my own version of Evaporate.js that was compatible w/ most S3-compatible buckets. Here's the code for it: https://github.com/faisalsayed10/firefiles/blob/main/apps/web/util/upload/index.ts

Note: This was also two years ago, so I'm not sure how much this library has changed over time
