### ISSUE TITLE
Is available for typescript module?

### ISSUE THREAD

**Issue by Allan-Nava** [TTLabs/EvaporateJS#488]
I cannot import Evaporate

https://github.com/HiWay-Media/compress-nodejs/actions/runs/6531786084/job/17733665558
![Screenshot 2023-10-16 at 11 42 34](https://github.com/TTLabs/EvaporateJS/assets/22498435/2c674147-1cea-4d4e-952a-f4915953521e)

**Comment by stri8ed** [comment]
`npm install --save @types/evaporate`

**Comment by Allan-Nava** [comment]
> `npm install --save @types/evaporate`

Thanks!
