### ISSUE TITLE
Use official aws-sdk.

### ISSUE THREAD

**Issue by dconnolly** [TTLabs/EvaporateJS#52]
https://github.com/aws/aws-sdk-js has existed for a few months at least, and includes official implementations of things like uploadPart, completeMultipartUpload, etc. It's probably a good idea to use those officially maintained and tested methods.

**Comment by psugihara** [comment]
My problem with the official aws-sdk is that it's over 250kb minified: https://github.com/aws/aws-sdk-js/blob/master/dist/aws-sdk.min.js

**Comment by tomsaffell** [comment]
There seems to be consensus of opinion not to do this, so I'm closing this issue.
