### ISSUE TITLE
Question: Presigned URLs and Encryption Support

### ISSUE THREAD

**Issue by bhatti** [TTLabs/EvaporateJS#54]
I am evaluating your Evaporate for uploading documents to s3. I have got the basic example working but I have a couple of questions. First, is your auth_sign method same as pre-signed s3 urls, if not how can I add its support. Second, is there a way to add encryption to the upload function or should I use server side encryption? 

Thanks.

**Comment by Koushik-Sarkar** [comment]
@tomsaffell The presigned URL has expired time support. Does there is any mechanism where the generated signature can be expired after a certain time(Like the presigned URL)?

**Comment by shivalkondwar** [comment]
> Thanks for your response. After a bit of testing, I found that auth_sign signature would work for me. As far as encryption, Amazon supports automatic encryption of entire bucket and I was able to add proper headers to the request to allow it from the client.

May I know how you used evaporateJS for uploading using Pre-Signed Url
