### ISSUE TITLE
Change config on the fly

### ISSUE THREAD

**Issue by michaelsharpe** [TTLabs/EvaporateJS#61]
I was just wondering if there is any way that I can change the configuration for each file.  I have an upload service that has a unique signerUrl and AWS public key per upload.  Is this possible without any major overhauls?

Thanks for the great software!

**Comment by tomsaffell** [comment]
@michaelsharpe thanks! it shouldnt be too hard. I dont have time to do it right now, but you basically just need to change the two lines linked below to check 'me'. something like

`var url = (me.signerUrl || con.signerUrl)+'?to_sign='+makeStringToSign(authRequester);`'

and then set the signerUrl property in the object you pass to .add()

https://github.com/TTLabs/EvaporateJS/blob/2b5535c179673f8f6199b70bc1a272cc37e94345/evaporate.js#L612

https://github.com/TTLabs/EvaporateJS/blob/2b5535c179673f8f6199b70bc1a272cc37e94345/evaporate.js#L661

when you get it working please send a PR :)

sorry for the slow response over Christmas..
