### ISSUE TITLE
Dropzone to upload

### ISSUE THREAD

**Issue by nguyenxuantuong** [TTLabs/EvaporateJS#66]
I am wondering if there is any way to enable dropzone for the upload component, so that instead of clicking to upload, people can drag the file to the upload zone to start upload the component. It would be helpful to have the dropzone setting as jquery file upload. Thanks.

**Comment by kberryman** [comment]
This is probably out of the responsibilities of this library.  This library only handles the actual upload of the files to S3.  You can write any component that you want to get the files from the users computer to the the Evaporate library.  The AngalurJS upload directive that I wrote to use Evaporate for our system allows for both choosing files from the file picker or dropping the files in a drop-zone.  You should be able to modify which ever file upload UI-element that you want to use Evaporate to actually do the upload.

**Comment by tomsaffell** [comment]
@kberryman I agree. Thanks for explaining it. I'll close this issue.
