### ISSUE TITLE
Cannot retrieve ETag headers while uploading files

### ISSUE THREAD

**Issue by maxwellE** [TTLabs/EvaporateJS#7]
I cannot seem to retrieve the ETag from the multipart upload response headers. I can successfully upload each chunk of the file but when it comes time to complete the multipart upload I am seeing this error:

``` xml
<Error><Code>InvalidPart</Code><Message>One or more of the specified parts could not be found.  The part may not have been uploaded, or the specified entity tag may not match the part's entity tag.</Message><UploadId>cawD5yowF97n6lErE88PcRtNfz8qeZIcoSLuWk77yPVq0.SgpbcRT_ShZjGnFFB61Vyq.caQGCPx28bSR_CaEA--</UploadId><ETag>null</ETag><RequestId>A8DB1B2F4F3F3C34</RequestId><HostId>/hQ8RMrnOYwtxWrOFD1vvNixxUAVmmQOqjXSPMsjDQ7qcBuQWBggINpa4IPGRagX</HostId><PartNumber>1</PartNumber></Error>
```

This is the error I see when I am uploading each chunk

![image](https://cloud.githubusercontent.com/assets/566328/2920525/05246590-d6e8-11e3-9115-cb3f3f532dff.png)

I am running the application using the example python script provided and have only added my bucket and AWS key.

**Comment by benbowler** [comment]
I'm getting " Refused to get unsafe header "ETag" " which leads to this error. My CORS config has:

<ExposeHeader>ETag</ExposeHeader>
