### ISSUE TITLE
Support for AWS4 signature (required when using "eu-central-1")

### ISSUE THREAD

**Issue by handegar** [TTLabs/EvaporateJS#71]
Is there support for using the new AWS4 signature in EvaporateJS? This is required when connecting to buckets which are located in Frankfurt (eu-central-1).

I think the signing requires SHA256 instead of SHA1, but changing my signing-handler to use SHA256 only results in a fail-message:
"failed to get authorization (readyState=4) for initiate.  xhr.status: 200.  xhr.response: <...>"

Is it only the singing-handler which needs to be fixed? I found some thing here which might be interesting:
  http://docs.aws.amazon.com/general/latest/gr/sigv4-signed-request-examples.html

Any ideas?

**Comment by tomsaffell** [comment]
I'd like to see the exact response you're getting back from your application server for the signing request. Please can you screenshot the that part of the network panel in your browser's developer tools and post it here. 

When you say 

>"failed to get authorization (readyState=4) for initiate. xhr.status: 200. xhr.response: <...>"

Is the `<...>` literally what is showing in the console, or did you strip some details?

**Comment by handegar** [comment]
This is the complete message from the console:

```
authorizedSend() initiate
evaporate.js:696 failed to get authorization (readyState=4) for initiate.  xhr.status: 200.  xhr.response: 5106155a368468bb58cebf6ed3aba0202f2a8289353f91456495f35c198eca3e
index.js:47 WARN: failed to get authorization (readyState=4) for initiate.  xhr.status: 200.  xhr.response: 5106155a368468bb58cebf6ed3aba0202f2a8289353f91456495f35c198eca3e
index.js:50 ERR: Error onFailedAuth for step: initiate
evaporate.js:246 onInitiateError for FileUpload 0
evaporate.js:153 onFileUploadStatusChange
evaporate.js:167 processQueue   length: 1
```

My Network panel:
![screen shot 2015-03-26 at 10 48 26](https://cloud.githubusercontent.com/assets/9700325/6843719/c39a31d4-d3a5-11e4-8b48-e257c06ddcc6.png)

I have implemented my own AWS4 signer based on the official Python example from here: http://docs.aws.amazon.com/general/latest/gr/sigv4-signed-request-examples.html

I am not 100% sure if I am doing the signing correctly, though, as I had to rewrite it in Go. 

The reason I asked about AWS4 support in EvaporateJS is that the reply to this post mentions that this might be missing: http://stackoverflow.com/questions/26788411/evaporate-js-php-backend-cors-not-working-just-yet

**Comment by hacfi** [comment]
@handegar A screenshot of the `Response` tab would be helpful as well!

**Comment by handegar** [comment]
The Response tab containes the 'xhr.status' message from the console:
![screen shot 2015-03-26 at 11 22 59](https://cloud.githubusercontent.com/assets/9700325/6844288/96023f78-d3aa-11e4-8481-33d7a9d57ced.png)

I think one of the issues is that evaporate.js:688 will not accept responses with length > 28. I think AWS4 signatures are supposed to be 65 characters long. I am not 100% sure here as I am trying to figure out this myself (my signature response is 45 chars, so there is probably an error in my signer code as well.)

**Comment by hacfi** [comment]
@handegar Thanks - I was expecting a properly formatted response so I didn’t think `xhr.response: 5106155a368468bb58cebf6ed3aba0202f2a8289353f91456495f35c198eca3e` was the entire response. Will have a look at this soon.

**Comment by handegar** [comment]
I have now fixed my signer code to return a proper 65 byte hexadecimal-key. If I remove the "== 28" statement @ evaporate.js:688, this is the response I get from Amazon:

```
 <Error>
  <Code>SignatureDoesNotMatch</Code>
  <Message>
    The request signature we calculated does not match the signature you provided. Check your key and signing method.
  </Message>
  <AWSAccessKeyId>**MY-AWS-KEY**</AWSAccessKeyId>
  <StringToSign>POST



x-amz-acl:public-read
x-amz-date:Thu, 26 Mar 2015 11:36:56 GMT
  /elasticbeanstalk-eu-west-1-XYZ/rendra_projects%2Fproject-1234%2Fifc%2Ftest.ifc?uploads</StringToSign>
  <SignatureProvided>342e0ce67eea95023cf4b44b125b2875df1e4411d8520f76fb152c094431354e</SignatureProvided>
  <StringToSignBytes>50 4f 53 54 0a 0a 0a 0a 78 2d 61 6d 7a 2d 61 63 6c 3a 70 75 62 6c 69 63 2d 72 65 61 64 0a 78 2d 61 6d 7a 2d 64 61 74 65 3a 54 68 75 2c 20 32 36 20 4d 61 72 20 32 30 31 35 20 31 31 3a 33 36 3a 35 36 20 47 4d 54 0a 2f 65 6c 61 73 74 69 63 62 65 61 6e 73 74 61 6c 6b 2d 65 75 2d 77 65 73 74 2d 31 2d 38 33 34 36 35 39 37 31 38 38 31 32 2f 72 65 6e 64 72 61 5f 70 72 6f 6a 65 63 74 73 25 32 46 70 72 6f 6a 65 63 74 2d 31 32 33 34 25 32 46 69 66 63 25 32 46 74 65 73 74 2e 69 66 63 3f 75 70 6c 6f 61 64 73</StringToSignBytes>
  <RequestId>91054103367C06C4</RequestId>
  <HostId>WRa/ZvGAPCei7cX8Tjr64ejN2lT0/M4aljc8w4XZjxW6p/cNz39eYn2T7aWfrJUn</HostId>
</Error>
```

Does 'StringToSign' look correct? If so, then the problem is probably with my signer code.

**Comment by hacfi** [comment]
@handegar Not sure what’s wrong but you mentioned eu-central-1 earlier but the example contains eu-west-1. Will look into this on the weekend (need this myself at some point).

**Comment by handegar** [comment]
Hmm... my mistake. I'm testing against eu-west-1 because it supports both AWS2 and AWS4. I see  now that eu-central-1 does not accept the AWS4 signon attempts at all. The response I get with eu-central-1 is as follows:

```
<Error>
  <Code>InvalidRequest</Code>
  <Message>The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.</Message>
  <RequestId>1D0E5A50E61BCFCF</RequestId>
<HostId>AuqF+UXImaPo6olTz+eTRPpvS1+HksXxT8MokSkjJzGu7D7GVkf9NnTxAUB0oaZXUOSZwj85N5w=</HostId>
</Error>
```

**Comment by handegar** [comment]
I have investigated a bit more and I think there are at least two issues in evaporate.js which is missing for full AWS4 support:

1) line 688: The "if" check here is too strict as AWS4 keys are 65 bytes long
2) line 614: The "Authorization" part of the request header looks different for AWS4 (Ref: http://docs.aws.amazon.com/general/latest/gr/sigv4-add-signature-to-request.html), so it should probably look something like this:
```
  xhr.setRequestHeader('Authorization', 'AWS4-HMAC-SHA256 Credential='+con.aws_key+'/' + shortdate + '/' + region + '/s3/aws4_request, SignedHeaders=host;x-amz-date, Signature=' + requester.auth);
```

If I do a crude hack-around of these two issues, I now get the following reponse from Amazon:

```
<Error>
  <Code>UnsignedContentSHA256NotAllowed</Code>
  <Message>The provided 'x-amz-content-sha256' header must be a valid SHA256.</Message>
  <RequestId>77EAF2062B327AC4</RequestId>
  <HostId>JQgTUHRfz8sWunzLPFQ+qtSqCgC13/cGFeMe64chZoj2mUFthiGqUzOh+9oBDGytb0NCyTTbEEg=</HostId>
</Error>
```

If I add the following after the authorization "xhr.setRequestHeader(..)";

```
     xhr.setRequestHeader('x-amz-content-sha256', requester.auth);
```
(some documentation regarding this here: http://docs.aws.amazon.com/AmazonS3/latest/API/bucket-policy-s3-sigv4-conditions.html)

I get the following response:

```
<Error>
  <Code>SignatureDoesNotMatch</Code>
  <Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message>
  <AWSAccessKeyId>**AWS_ACCESS_KEY**</AWSAccessKeyId>
  <StringToSign>AWS4-HMAC-SHA256
Thu, 26 Mar 2015 13:48:46 GMT
20150204/eu-central-1/s3/aws4_request
82b7b9b5f1992eaf9062cac7c8019bfe1b2b3801d2ef94bf0b4959a9c7c50c47</StringToSign>
  <SignatureProvided>09dd10bbfb36876ed4718aca6ee318560ad526e6f2ac3831d01c4696e2845a6a</SignatureProvided>
  <StringToSignBytes>41 57 53 34 2d 48 4d 41 43 2d 53 48 41 32 35 36 0a 54 68 75 2c 20 32 36 20 4d 61 72 20 32 30 31 35 20 31 33 3a 34 38 3a 34 36 20 47 4d 54 0a 32 30 31 35 30 32 30 34 2f 65 75 2d 63 65 6e 74 72 61 6c 2d 31 2f 73 33 2f 61 77 73 34 5f 72 65 71 75 65 73 74 0a 38 32 62 37 62 39 62 35 66 31 39 39 32 65 61 66 39 30 36 32 63 61 63 37 63 38 30 31 39 62 66 65 31 62 32 62 33 38 30 31 64 32 65 66 39 34 62 66 30 62 34 39 35 39 61 39 63 37 63 35 30 63 34 37</StringToSignBytes>
  <CanonicalRequest>POST
/elasticbeanstalk-eu-central-1-XYZ/rendra_projects/project-1234/ifc/test.ifc
uploads=
host:s3-eu-central-1.amazonaws.com
x-amz-date:Thu, 26 Mar 2015 13:48:46 GMT

host;x-amz-date
09dd10bbfb36876ed4718aca6ee318560ad526e6f2ac3831d01c4696e2845a6a</CanonicalRequest>
  <CanonicalRequestBytes>50 4f 53 54 0a 2f 65 6c 61 73 74 69 63 62 65 61 6e 73 74 61 6c 6b 2d 65 75 2d 63 65 6e 74 72 61 6c 2d 31 2d 38 33 34 36 35 39 37 31 38 38 31 32 2f 72 65 6e 64 72 61 5f 70 72 6f 6a 65 63 74 73 2f 70 72 6f 6a 65 63 74 2d 31 32 33 34 2f 69 66 63 2f 74 65 73 74 2e 69 66 63 0a 75 70 6c 6f 61 64 73 3d 0a 68 6f 73 74 3a 73 33 2d 65 75 2d 63 65 6e 74 72 61 6c 2d 31 2e 61 6d 61 7a 6f 6e 61 77 73 2e 63 6f 6d 0a 78 2d 61 6d 7a 2d 64 61 74 65 3a 54 68 75 2c 20 32 36 20 4d 61 72 20 32 30 31 35 20 31 33 3a 34 38 3a 34 36 20 47 4d 54 0a 0a 68 6f 73 74 3b 78 2d 61 6d 7a 2d 64 61 74 65 0a 30 39 64 64 31 30 62 62 66 62 33 36 38 37 36 65 64 34 37 31 38 61 63 61 36 65 65 33 31 38 35 36 30 61 64 35 32 36 65 36 66 32 61 63 33 38 33 31 64 30 31 63 34 36 39 36 65 32 38 34 35 61 36 61</CanonicalRequestBytes>
  <RequestId>C12514F78F69594C</RequestId>
  <HostId>naNqsr0X0fEY1PAXnh1OOCQAH/aU1vU38HjgYHgcmfmCUZvggCjN9pIICz8hu2HdxvRXuRnVRU8=</HostId>
</Error>
```

Which is probably a good thing as Amazon now seems to accept the request as a correct AWS4 query. However the ```<StringToSign>``` does not seem to match EvaporateJS' "to_sign" string created @ evaporate.js:733 (if this is relevant at all, that is).

Anyways, I'll dig more into this tomorrow. Getting EvaporateJS to support AWS4 would be really cool as it will make it work with every Amazon center in the world :)

**Comment by choxy** [comment]
Thanks, for diggin' into AWS4!
Previously I used eu-west-1 (evaporatejs worked great), but because of better network performance today I switched my S3 and configs to eu-central-1, now I get the same 'Please use AWS4-HMAC-SHA256' error.
AWS4 support will be good upgrade for evaporatejs.

**Comment by tomsaffell** [comment]
sounds like some good progress is being made here. i agree with @handegar suggestions on checking length, different headers, etc. 

if there is anything (quick) that i can do to help then please ask!

**Comment by choxy** [comment]
Have you @handegar succeeded to implement AWS4? Are you planning to make a pull request with your fixes?

**Comment by handegar** [comment]
I had to let this issue rest for a bit due to pressing deadlines at work. When things calm down I'll hopefully be able to pick it up where I left and continue.

**Comment by dr-impossible** [comment]
The official AWS JS SDK (https://github.com/aws/aws-sdk-js) supports signature V4 and will also now automatically retry failed multipart pieces, much like EvaporateJS. I've been able to use this to successfully upload files to S3 in the cn-north-1 region, which also requires V4 signatures.

One difference however, is that signing of the upload happens entirely on the client side, so you'll need to provide the client with credentials. You could use STS on the server side to issue temporary AWS credentials with limited access necessary to upload the file.

```JavaScript

var s3 = new AWS.S3({
    accessKeyId: 'AKIA...',
    secretAccessKey: 'dakjdhkjhdkljwlkdj...',
    region: 'eu-central-1'
});

var managedUpload = s3.upload({
    ACL: 'public-read',
    Body: file,
    Bucket: 'my-bucket-name',
    Key: '/path/to/file/in/bucket.ext'
}, function (error, data) {
    // upload finished
    if (error) {
        // upload failed
    } else if (data) { 
        // upload succeeded
    }
});

managedUpload.on('httpUploadProgress', function (progress) {
    // progress event handler
    // progress.loaded = number of bytes uploaded so far
    // progress.total = size of file in bytes (may be undefined if not yet known)
});
```

**Comment by e-tip** [comment]
Is there any news on this issue ?

**Comment by bikeath1337** [comment]
For what it's worth, the official AWS JS SDK (https://github.com/aws/aws-sdk-js) does support retries but it does NOT support MD5 digests for anything but bodies of type `String`.

As of v1.0.0, EvaporateJS does support MD5 digest verification.  Do we still need to address the AWS4 signature? We would like to make it work internationally, too.

**Comment by dr-impossible** [comment]
I think it's a case of where all regions support V4, but the newest regions (currently just Beijing (cn-north-1) and Frankfurt (eu-central-1)) do not, and might never, support V2 signatures. To the best of my knowledge, AWS has not yet declared any sunset date for V2 signatures.

**Comment by bikeath1337** [comment]
What's not clear to me is whether it works now or if we still need to consider enhancing EvaporateJS. I can't imagine that adding support for the more secure signature would be very challenging and doing things securely is a good thing. :)

**Comment by dr-impossible** [comment]
Agreed. The V4 process is definitely an improvement over V2. Amazon has some detailed documentation on the process here http://docs.aws.amazon.com/general/latest/gr/signature-version-4.html

**Comment by tomsaffell** [comment]
FWIW, I this does seem like a feature EvaporateJS should have, but as @handegar says, adding a new signing system is a fair amount of work. I'm not at all familiar with v4 signing, and dont have the BW to look into it, sorry. But I'm sure it's doable, and I'm sure other folks would like to use it, we just need someone to write it ... :)

**Comment by bikeath1337** [comment]
I've done a lot of this stuff and will probably look at it in the next couple of weeks.

**Comment by tomsaffell** [comment]
@bikeath1337 great - thanks! maybe adding a second signing method will be a forcing function for a refactoring?

**Comment by bikeath1337** [comment]
Hopefully a min-breaking option for those who need it.

**Comment by bikeath1337** [comment]
A non-breaking...

**Comment by bikeath1337** [comment]
I added an example using the AWS SDK for JavaScript to calculate the md5 checksum using the cryptoMd5Method setting, making it easier to add this feature later..

**Comment by bikeath1337** [comment]
I have a test branch for this working to a point but I'm getting some odd mid-transport failures on the PUTs. Will work with AWS support on that.

**Comment by flosky** [comment]
+1
Since we are sitting in Germany we run everything out of Region eu-central-1. I was very excited to find a lib that works out of the box but then it didn't for me because V4 is not supported. Took me a while to figure that this was the problem. Thankgs guys, keep up the good work.

**Comment by bikeath1337** [comment]
Thanks, all. I have another branch that is on hold that supports V4 signatures. Unfortunately, as you probably all know, it's a pretty involved process. I've got it working up to a point and have engaged AWS support for help in an area that is baffling (the PUTS abort automatically after _n_ bytes sent.

Will keep everyone posted.

**Comment by flosky** [comment]
I have also been in touch with the Amazon support and am still waiting for a reply.
In the mean time I have fixed it and it works now for me.
This my node.js erver side code to create the policy and signature (note that the signature must be hex encoded)

        app.use('/sign_s3', function(req, res) {

            const date = new Date().toISOString().replace(/[\.\-:]/gi, "").substr(0, 15) + "Z";
            const dateNowRaw = date.substr(0, date.indexOf("T"));

            const expirationDate = new Date();
            expirationDate.setHours(expirationDate.getHours() + 1);
            const expiration = expirationDate.toISOString();

            const credentials = '<myAwsId>/' + dateNowRaw + '/eu-central-1/s3/aws4_request';
            const policy = {
                expiration: expiration,
                conditions: [
                    {"bucket": "<myBucketName>"},
                    {"acl": "private"},
                    ["starts-with", "$key", ''],
                    ['starts-with', '$Content-Type', ''],
                    {"x-amz-credential": credentials},
                    {"x-amz-algorithm": "AWS4-HMAC-SHA256"},
                    {"x-amz-date": date}
                ]
            };

            const base64Policy = new Buffer(JSON.stringify(policy), "utf-8").toString("base64");

            const dateKey = crypto.createHmac('sha256', "AWS4" + "<myPrivateAwsKey>").update(dateNowRaw).digest();
            const dateRegionKey = crypto.createHmac('sha256', dateKey).update('eu-central-1').digest();
            const dateRegionServiceKey = crypto.createHmac('sha256', dateRegionKey).update('s3').digest();
            const signingKey = crypto.createHmac('sha256', dateRegionServiceKey).update('aws4_request').digest();

            const signature = crypto.createHmac('sha256', signingKey).update(base64Policy).digest('hex');
           
            res.status(200).json({
                signature: signature,
                policy: base64Policy,
                date: date,
                credentials: credentials,
                expiration: expiration
            });
        });

On the client I am currently using ng-file-upload which sends a multipart form data request

                var signature = response.data.signature;
                var policyBase64 = response.data.policy;
                var date = response.data.date;
                var credentials = response.data.credentials;
                var expiration = response.data.expiration;

                Upload.upload({
                    url: 'https://<myBucketName>.s3.amazonaws.com/',
                    method: 'POST',
                    data: {
                        key: file.name,
                        acl: 'private',
                        Policy: policyBase64,
                        'X-Amz-Credential' : credentials,
                        'X-Amz-Algorithm': 'AWS4-HMAC-SHA256',
                        'X-Amz-Date': date,
                        'X-Amz-Signature': signature,
                        "Content-Type": contentType,
                        file: file
                    }
                }).then(successHandler, errorHandler, progressHandler);

Hope that helps

**Comment by bikeath1337** [comment]
If you have a branch built off of mine that I can view, I will take some time to integrate it, @flosky. Thank you so much.

**Comment by flosky** [comment]
@bikeath1337 This week I'll be pretty swamped (because I have to rebuild most of our file upload) but I'm happy to integrate some code into your branch as soon as I can. Whats the branch I should use?

**Comment by bikeath1337** [comment]
Hi, @flosky , I was working on this in another project so I just brought those very WIP changes current with master.

I was using a local Ruby on Rails controller to do the signing and that controller is not here; however, I assume you have one you can use. 

You'll see I added a few new config options to create crypto methods that are pluggable. These worked well for me.

I was able to get everything working until what appeared to be the part PUTs. The browser debug window appears to upload the stream and then aborted due to an AWS trigger.

Please remember that this is very WIP. I quickly threw together some methods to see how far I could get. I think that because these changes completely replace a core flow of the existing branch, we want to be very careful how we switch between the two methods.

**Comment by bikeath1337** [comment]
And it's on my fork, branch `v4sign`, currently SHA dc780e6.

**Comment by bikeath1337** [comment]
@handegar @tomsaffell @hacfi @choxy @dr-impossible @e-tip @flosky @SamPotts @fd 

I put in a PR for this feature. It's #154 . I put it through it's paces and it came out fine. Should be fully backward compatible but would appreciate some additional eyes and testing if you're up for it.

**Comment by SamPotts** [comment]
Sorry I didn't get back to you on this. I've been on leave. I wouldn't have been able to get it into production at this point.
