### ISSUE TITLE
Server should examine request before signing

### ISSUE THREAD

**Issue by psugihara** [TTLabs/EvaporateJS#73]
This was brought up [in another issue](https://github.com/TTLabs/EvaporateJS/issues/52#issuecomment-62471963).

Basically, in most cases the signing request should be checked server-side to make sure the user should have access to the place they upload to. It would be nice if this kind of check were included in the example. Blindly signing will result in a malicious user being able to overwrite every file in the bucket.

**Comment by tomsaffell** [comment]
Hi @psugihara I absolutely agree that the server should check whether the user is authorized before returning the signed request. Our app certainly does this! This is why signParams are supported - so you can include any information required for that authorization logic. 

Having said that, the implementation of the signing logic it outside the scope of EvaporateJS. We provide a *trivial* example to help get people started. I think it would be a good idea to include a comment in there about authorization. But no actual code - it would do more harm than good IMO. 

So I'm going to close this issue. You're welcome to open a new one suggesting the comment in the example signer code, or better yet, submit a PR and I'll accept it!

thanks!
