### ISSUE TITLE
Request denied when using temporary security credentials (IAM roles) and server side has multiple ec2 instances

### ISSUE THREAD

**Issue by xli** [TTLabs/EvaporateJS#76]
As temporary security credentials (IAM roles) will have different access key id and secure token on different EC2 machine, current implementation will get 403 (Forbidden) when the first request get security-token and a following request to sign the request params hits different ec2 instance.
These seems need to be setup in one request to server to get all params (including anything need to be signed) and signed signature.

**Comment by xli** [comment]
Working on a pull request to fix this, may update this issue later

**Comment by xli** [comment]
It turns out that you have to use same temporary security credentials to sign all s3 multiparts upload requests. 
But there are 3 steps to finish the work: 
1. Init to get upload id
2. Upload parts with upload id
3. Complete the upload at the end with ETags respond from uploading parts

When you have multiple EC2 instances behind an ELB, you can't hit same EC2 instance to sign all these 3 steps requests.

The only way to make it work is share one EC2 instance's temp secure access key cross all EC2 instances for signing multiparts uploading requests.

So, there is nothing EvaporateJS can do. I'll just close this ticket.

**Comment by tomsaffell** [comment]
@xli thanks for documenting this. if you think it's worthwhile, please update the readme docs and send a PR for that! thanks again, tom.
