### ISSUE TITLE
Cannot retrieve ETag headers while uploading files from Android stock browser

### ISSUE THREAD

**Issue by primess** [TTLabs/EvaporateJS#77]
( in upload.on200)
var eTag = xhr.getResponseHeader('ETag')
This returns null when running in Android 4.x versions until version 4.4 on StockBroswer even though I see in Fiddler that eTag is returned.
This seems to be a bug in Android implementation - https://bugs.webkit.org/show_bug.cgi?id=41210
(Cross Origin XMLHttpRequest can not expose headers indicated in Access-Control-Expose-Headers HTTP Response Header)
Works on Stock browser in versions 4.4+

**Comment by tomsaffell** [comment]
@primess interesting. as you say, this looks like a bug in android. a few options on how to proceeed from here:

1. find a work around, test it, send a PR
2. give up on workaround, update the 'supported' function so it returns false for this browser, send a PR
3. update the readme / docs to make a note of this, send a PR

once we've done one of those I think we can close this issue

thanks for your help

tom

**Comment by bikeath1337** [comment]
This bug has reportedly been fixed @primess .

https://bugs.webkit.org/show_bug.cgi?id=41210#c31
