### ISSUE TITLE
Tag for 0.0.2

### ISSUE THREAD

**Issue by mkilling** [TTLabs/EvaporateJS#81]
I'd like to pull in EvaporateJS into a Rails project using https://rails-assets.org/. However to do this the repository needs to have semver-compliant git tags.

Would it be possible to create a tag for the 0.0.2 release in this Github repo?

**Comment by tomsaffell** [comment]
sure. is that something you can do via a PR? or do i must i do it?

**Comment by mkilling** [comment]
Unfortunately you can’t add tags to a PR (http://stackoverflow.com/questions/12278660/adding-tags-to-a-pull-request <http://stackoverflow.com/questions/12278660/adding-tags-to-a-pull-request>). It would be great if you could do it yourself!

**Comment by musha68k** [comment]
:+1: Bower depends on the existence of Tags as well. I am sure lots of people would be much obliged! 🎩

**Comment by bikeath1337** [comment]
@mkilling and @musha68k check out progress. we finally left beta and have tagged 1.0.0 and 1.0.1.

I'm a Rails developer as well, have you considered creating a Gem for EvaporateJS?
