### ISSUE TITLE
Uncaught InvalidStateError: Failed to execute 'setRequestHeader' on 'XMLHttpRequest': The object's state must be OPENED

### ISSUE THREAD

**Issue by jlines** [TTLabs/EvaporateJS#83]
The url signing endpoint that I am using requires Authentication, therefore I need to configure evaporate.add calls with the signHeaders option which causes the error in the subject.

signHeaders: {
	Authorization:'Bearer ' + Authentication.token
}, 

I was able to alter the evaporate library to set the headers after the call to xhr.open which solved the issue. Perhaps I can submit a pull request

**Comment by tomsaffell** [comment]
closed by https://github.com/TTLabs/EvaporateJS/pull/84
