### ISSUE TITLE
could you add a license file to the repository?

### ISSUE THREAD

**Issue by xli** [TTLabs/EvaporateJS#87]
Just make it easier for people want to use this lib for distribution

**Comment by tomsaffell** [comment]
hi @xli, I may need a little education here... There is a statement at the top of the evaporate.js file concerning copyright, use, redistribution, modification, etc. Please can you explain to me what we gain by having a separate license file (a genuine question, I'm no expert at this :). Also, if we add a license file, does it replace the statement at the top of evaporate.js file, or supplement it? thanks, tom

**Comment by xli** [comment]
Hi @tomsaffell, I don't need this anymore.
Just thought including a license file or mention license in readme will be easier for others to know what's license of EvaporateJS.

**Comment by tomsaffell** [comment]
got it. it's BSD 3-clause
http://opensource.org/licenses/BSD-3-Clause
