### ISSUE TITLE
Best way to control the S3 object key?

### ISSUE THREAD

**Issue by bschwind** [TTLabs/EvaporateJS#89]
It seems the client can completely control what key an object gets when uploaded to S3. If you wanted to enforce a particular key from the server, what are the best practices?

When the signing URL is called, I could technically extract the object key from the `to_sign` data, but I was wondering if there was a more elegant approach.

**Comment by tomsaffell** [comment]
here's what we do:

1. prior to uploading a file, our client calls server to get a new 'asset id'
2. the client then uses that asset id as the 'key' for S3 when uploading

Of course, that's still trusting the client... If you wanted to make it more secure you could do:

3. upon receiving the singing request, and before returning the signature, the server checks whether that asset id belongs to the user and is 'allowed' to upload to S3 using it (e.g. not used it before)

To do part 3 you'd currently need to extract the key from the 'to_sign' string, but you could easily enhance EvaporateJS to send the key as another request parameter in the signing request. 

Hope that helps. Let me know what you end up doing. If you enhance EvaporateJS in a way that might be useful for other people then please send me a PR!

tom

**Comment by tomsaffell** [comment]
@bschwind

**Comment by bschwind** [comment]
Thanks for the quick response!

I guess the main thing I'm worried about is a client intending to overwrite an existing object key. I could send the key as another request parameter but the client could just as easily pass in the "correct" object key while getting a different key signed. So I think the best way for now is to simply look for the object key in the `to_sign` string and make sure it's what the client originally requested.

To avoid having to do a DB lookup every time I get a sign request, maybe I'll use something like a JSON Web Token to hold the object key, and verify the token's authenticity (and that its contents match what is being signed).

I'll have to think about it more, but thanks for answering!

**Comment by tomsaffell** [comment]
>the client could just as easily pass in the "correct" object key while getting a different key signed

good point! Extracting from to_sign is the better way.

>To avoid having to do a DB lookup every time.... JSON Web Token 

Or you could put that info in memcache if that's available to you

**Comment by bschwind** [comment]
That's true, there's quite a few ways I could do this. JWT jumped to mind because I already use those for authentication in my app. Thanks for this discussion!

**Comment by kyranb** [comment]
Is there an example anywhere of how to implement this and extract the key from the `to_sign` string?

**Comment by bschwind** [comment]
The `to_sign` string looks something like this:

```
PUT



x-amz-date:Wed, 26 Aug 2015 02:31:30 GMT
/YOUR_BUCKET/OBJECT_KEY?partNumber=1&uploadId=SOME_UPLOAD_ID
```

But you'll have to run a URL decoder on it so you don't get things like %2f instead of a forward slash. I haven't looked at the code too closely but [here](https://github.com/TTLabs/EvaporateJS/blob/master/evaporate.js#L733) is where the `to_sign` string is constructed. It looks like the object key should always be at the front of the last line in the `to_sign` string.

**Comment by tomsaffell** [comment]
there's a few links in the source code that might help to, like this one:
  http://docs.aws.amazon.com/AmazonS3/latest/dev/RESTAuthentication.html#ConstructingTheAuthenticationHeader

**Comment by bschwind** [comment]
Well, here's what I ended up doing:

https://gist.github.com/bschwind/277a078d59a70d451d0d

I've tested it and it seems to work well for my usage scenarios. Not sure how good my assumptions are on the object key always being at the beginning of the last line, but for now it works.

**Comment by chanon** [comment]
Is this still possible with AWS Signature v4 signing?
