### ISSUE TITLE
Query

### ISSUE THREAD

**Issue by sam1111** [TTLabs/EvaporateJS#94]
The comments mention calculating MD5 and sending them to server and sending ETags of each part to server on part complete to provide support for resumability across different sessions. Can you please elaborate a bit more on how do you plan to use MD5 and ETags to achieve this? I am planning to implement it.

**Comment by bikeath1337** [comment]
The MD5 Digest feature supported by AWS S3 multipart uploads has been implemented and is available now as of v1.0.0.
